
## Script for all words in crosswords.

init -10 python:
    FULL_WORDS = [
        "Gaia",
        "Kali",
        "Venus",
        "Inanna",
        "Judith",
        "Sapphó",
        "Sophía",
        "Aspasia",
        "Hypatia",
        "Amazónes",
        "Marcella",
        "Theodora",
        "Boadaceia",
        "Naomh Bríd",
        "Sacajawea",
        "Serpentes",
        "Elizabeth I",
        "Ethel Smyth",
        "Hatshepsut",
        "Isabella d’Este",
        "Natalie Barney",
        "Susan B. Anthony",
        "Virginia Woolf",
        "Anne Hutchinson",
        "Emily Dickinson",
        "Georgia O’Keeffe",
        "Margaret Sanger",
        "Sojourner Truth",
        "Caroline Herschel",
        "Christine de Pizan",
        "Aliénor d’Aquitaine",
        "Petronilla de Meath",
        "Trotula de Ruggiero",
        "Elizabeth Blackwell",
        "Hildegard von Bingen",
        "Mary Wollstonecraft",
        "Anna Maria van Schurman",
        "Artemisia Gentileschi",
        "Hrotsvit von Gandersheim"
    ]

    RENDERED_WORDS = [
        "Gaia",
        "Kali",
        "Venus",
        "Inanna",
        "Judith",
        "Sappho",
        "Sophia",
        "Aspasia",
        "Hypatia",
        "Amazones",
        "Marcella",
        "Theodora",
        "Boadaceia",
        "NaomhBrid",
        "Sacajawea",
        "Serpentes",
        "ElizabethI",
        "EthelSmyth",
        "Hatshepsut",
        "IsabelladEste",
        "NatalieBarney",
        "SusanBAnthony",
        "VirginiaWoolf",
        "AnneHutchinson",
        "EmilyDickinson",
        "GeorgiaOKeeffe",
        "MargaretSanger",
        "SojournerTruth",
        "CarolineHerschel",
        "ChristinedePizan",
        "AlienordAquitaine",
        "PetronilladeMeath",
        "TrotuladeRuggiero",
        "ElizabethBlackwell",
        "HildegardvonBingen",
        "MaryWollstonecraft",
        "AnnaMariavanSchurman",
        "ArtemisiaGentileschi",
        "HrotsvitvonGandersheim"
    ]

    COORD_WORDS = [
        [600, 840, "down"],
        [1530, 420, "right"],
        [900, 870, "right"],
        [900, 180, "down"],
        [1350, 90, "down"],
        [240, 900, "right"],
        [720, 840, "right"],
        [870, 480, "right"],
        [1620, 480, "down"],
        [1050, 810, "right"],
        [1590, 240, "down"],
        [810, 120, "down"],
        [1560, 600, "down"],
        [1110, 180, "down"],
        [660, 330, "right"],
        [330, 810, "right"],
        [1410, 600, "right"],
        [660, 960, "right"],
        [1080, 210, "right"],
        [330, 300, "down"],
        [1470, 450, "down"],
        [1200, 600, "down"],
        [480, 900, "right"],
        [210, 360, "down"],
        [960, 420, "right"],
        [1200, 360, "right"],
        [690, 210, "down"],
        [1110, 510, "right"],
        [810, 450, "down"],
        [1290, 300, "down"],
        [390, 270, "down"],
        [930, 480, "down"],
        [540, 270, "down"],
        [630, 720, "right"],
        [450, 330, "down"],
        [270, 450, "down"],
        [750, 180, "down"],
        [720, 660, "right"],
        [210, 600, "right"]
    ]
