
## Dictionary in Spanish for all items of gallery.


init -10 python:
    gallery_dict_es = {
        0: {
            "name": "Ada Lovelace",
            "content": "Primera programadora informática. Ada Lovelace estaba fascinada por las máquinas. A los 17 años, conoció a Charles Babbage, el diseñador de la {i}máquina diferencial{/i}, el primer ordenador de la historia que podía realizar cálculos con números.\nImpresionada por los inventos, se interesó por la {i}máquina analítica{/i}, un dispositivo que podría llevar a cabo cálculos matemáticos más complejos. Ella tuvo la idea revolucionaria de que la {i}máquina analítica{/i} tratara números, letras y símbolos mediante una serie de instrucciones, conocidas como algoritmos. Además, ideó un sistema para repetir una secuencia de operaciones, conocido como bucle ({i}looping{/i}).\nDesafortunadamente, no vivió suficiente para ver sus ideas hacerse realidad. Murió a los 36 años, pobre y enferma. No fue hasta casi un siglo después cuando Alan Mathison Turing le reconoció su genialidad cuando trabajaba con los primeros ordenadores modernos. Es considerada {i}profeta de la era informática{/i} por su perspectiva visionaria sobre muchas de las funcionalidades de los ordenadores."
        },
        1: {
            "name": "Marie Curie",
            "content": "Eminente científica. Aunque pudo ir a la universidad, su vida fue muy pobre y nada fácil, hasta que conoció a Pierre Curie, con quien formó una família. Ambos trabajaban juntos para investigar la radioactividad, descubrieron el polonio y el radio. En 1903, consiguieron el Premio Nobel, y Marie se convirtió en la primera mujer en ganar uno, aunque ocho años más tarde consiguió el de Química. Después de la muerte accidentada de Pierre, lo sustituyó y se convirtió en la primera profesora de la Universidad de la Sorbona. Asimismo, Marie contribuyó a desarrollar máquinas portátiles de rayos X para llevarlas en ambulancias, las {i}pequeñas curies{/i}. Además de ser la conductora, formó a médicos y ayudantes para enseñarles a usar el equipo.\nMuchos de los hombres con quien trabajó la trataron muy mal y le pagaron muy poco, de manera que continuaba teniendo una vida muy pobre. Ignorando su peligrosidad, la compañía de tubos de ensayo llenos de radioactividad la hizo enfermar y murió tiempo más tarde.\nHoy en día, el equipo se sigue usando en la medicina y gracias a ella millones de personas han podido ser tratadas y curadas. Marie Curie fue una de las mejores científicas de la historia."
        },
        2: {
            "name": "Frida Kahlo",
            "content": "Pionera de la pintura mexicana y heroína feminista. A los 18 años, Frida Kahlo sufrió un accidente de tráfico y casi pierde la vida. Los meses de recuperación fueron duros, los pasó en cama, plena de aburrimiento y tristeza. Fue en ese momento cuando decidió iniciarse en la pintura.\n Cuando se encontró mejor, se emparejó con Diego Rivera, con quien no pudo tener hijos debido a las lesiones del accidente. Esta gran tristeza fue inspiración en muchas de sus cuadros, igual que algunas de sus mascotas.\nSus obras eran muy personales, 55 de sus 143 pinturas son autoretratos. Por costumbre, se dibujaba con dureza y poco atractiva, cejas espesas y bigote.\nMientras ella se hacía famosa, su salud empeoraba. Murió a los 47 años. Hoy en día, es un ejemplo a seguir porque demostró que las mujeres, a pesar de los obstáculos, pueden hacer todo aquello que se propongan. Es admirada por su creatividad, su audacia y por seguir su corazón."
        },
        3: {
            "name": "Maria Montessori",
            "content": "Médica y profesora. Fue la primera médica de Italia. Interesada en los derechos de las mujeres y de los niños, dedicó prácticamente toda su vida a tratar con ellos. Trabajó con niños con problemas de aprendizaje y diversidad funcional. Creía que todos los infantes nacen con potencial que los adultos deben ayudarles a descubrir, independientemente de su entorno originario. Estas ideas eran muy novedosas para la época, con lo cual Maria se tuvo que esforzar mucho para cambiar la mentalidad de la gente.\nMaria Montessori creó la escuela {i}Casa dei bambini{/i}, en la cual se trataba a los infantes con la dignidad que merecían, por este motivo les enseñó a cuidarse, a sonarse la nariz y a atarse los botones de los abrigos a ellos solos. Además, escribió {i}El método Montessori{/i}, cuyo narrativa expone sus ideas para crear un entorno dono los infantes pudieran explorar y aprender a su propio ritmo, y donde los profesores los acompañaran.\nElla se convirtió en pionera del pensamiento educativo. Compartió sus ideas alrededor del mundo sobre la educación convencional y la educación para infantes con necesidades especiales, cuyo impacto cambió la visión y comprensión que se tenía de la infancia. Fue nominada tres veces al Premio Nobel de la Paz antes de fallecer."
        },
        4: {
            "name": "Wangai Maathai",
            "content": "Activista por el medio ambiente. Wangari Muta Maathai, apasionada desde pequeña por la naturaleza, fue la primera mujer de África oriental y central en doctorarse en una universidad. Pero ella aspiraba a realizar un cambio aún mayor.\nEntonces, Kenia estaba sufriendo problemas debido a la deforestación y la malnutrición. A Wangari le ocurrió una idea genial, conocida como el Movimiento Cinturón Verde: cualquier persona puede cambiar el mundo salvando a un árbol cada vez. De esta manera, a partir de 1977, esta idea ayudó a diferentes comunidades locales a plantar más de cincuenta y un millones de árboles en Kenia y consiguió que el gobierno protegiera más el medio ambiente, haciendo que la agricultura no destruyera los bosques y enseñando a los habitantes a reducir, reusar y reciclar.\nAdemás, como pionera en la educación, consideraba que solamente a través de la educación podría encontrarse una solución para la extensión del SIDA en África. Así, escribió cuatro libros sobre ecología y África, y fundó el Instituto Wangari Maathai por la Paz y los Estudios Medio Ambientales.\nEn 2004, recibió el Premio Nobel de la Paz, convirtiéndose así en la primera mujer africana en ganarlo. Ella dedicó su vida a ayudar a las mujeres y a mejorar el medio ambiente, cuya preservación y protección ella deseaba para que todo el mundo pudiera vivir en paz y harmonía."
        },
        5: {
            "name": "Hedy Lamarr",
            "content": "Inventora y actriz superdotada. Formada en interpretación, empezó destacando en {i}Ecstasy{/i}, película polémica, cuyo cuerpo desnudo y su rostro aparecían durante un orgasmo. Por este motivo, fue obligada a casarse con Fritz Mandl, quién la forzó a asistir a sus reuniones de trabajo pero ella aprovechaba para aprender sobre la última tecnología armamentística nazi. No obstante, más tarde consiguió huir a los Estados Unidos, y aunque las películas interpretadas fueran un desastre, se convirtió en la estrella de los años 30.\nHedy conocía las prácticas nazis y decidió ayudar a los aliados en la Segunda Guerra Mundial. El año 1942, inscribió la patente de un método de codificación de transmisiones, el espectro ensanchado por salto de frecuencias, método usado por las actuales tecnologías inalámbricas.\nElla no consiguió nunca dinero por la patente, que caducó sin ser usada, y el reconocimiento tardó en llegar. Su vida personal no fue muy afortunada y su carrera cinematográfica sufrió un fuerte descens, que la llevó a la obsesión por la cirugía estética y el mundo de las pastillas. En Austria, el día 9 de noviembre se celebra el Día del Inventor en su honor."
        }
    }
