
## Dictionary in English for all items of gallery.


init -10 python:
    gallery_dict_en = {
        0: {
            "name": "Ada Lovelace",
            "content": "First computer programmer, Ada Lovelace was fascinated by machines. At the age of 17, she met Charles Babbage, the designer of the {i}difference machine{/i}, the first computer in history that could perform mathematical calculus.\nImpressed by the inventions, she became interested by the {i}Analytical Engine{/i}, a device capable of more complex mathematical calculus. She then had the revolutionary idea that the {i}Analytical Engine{/i} could handle names, letters and symbols by a series of instructions, known as algorithm. Even more, she had the idea of a system that could perform a sequence of instructions known as {i}looping{/i}.\nSadly, she could not live long enough to see her ideas come true. She died at the age of 36, poor and ill. It wasn't until almost a century later Alan Mathison Turing recognized her genius while he was working on the first modern computers. She is considered a {i}Computer Age prophet{/i} due to her visionay view about many of the capabilities of modern computers."
        },
        1: {
            "name": "Marie Curie",
            "content": "Scientific eminence. Even being able to go to the university, her life was very poor and tough until she met Pierre Curie, with whom she formed a family. Both worked together researching the radioactivity and they discovered the plutonium and radium. In 1903 both were granted the Nobel Prize in Physics, so Marie was the first woman to win the prize, although eight years later she won the Nobel in Chemistry. After the tragic death of Pierre, she substituded him and became the first female teacher at the Sorbonne University. Even more, Marie contributed to develop portable X-ray machines that could fit in the ambulances, the {i}little curies{/i}. Besides being the driver, she instructed doctors and nurses to teach them how to use this equipment.\nMany of the men whom she worked with were very mean with her and the university payed her a low salary, so her life was still very poor. Ignoring the danger, the continuous presence of test tubes filled with radioactive materials made her get sick and she died shortly after.\nNowadays, the equipment she developed is still being used and she helped countless people to be treated and cured. Marie Curie is among the best scientific researchers in history."
        },
        2: {
            "name": "Frida Kahlo",
            "content": "Mexican painting pioneer and feminist hero. At the age of 18, Frida Kahlo suffered a road accident, nearly being killed. The time while recovering was hard stuck on the bed, full of boredom and sadness. It was then when she decided to begin painting.\nWhen she felt better, she married Diego Rivera, but could not give birth to any children due to injuries from her accident. This great sadness inspired her for many of her paintings, as well as some of her pets.\nHer paintings were very personal, 55 out of her 143 paintings are self-portraits. She usually drew herself as a tough and less atractive person, thick eyebrows and moustache.\nMeanwhile she was getting famous, her health condition was getting poorer until she died at the age of 47. Nowadays, she is an example to follow because she proved that women, even with obstacles, are able to do everything they proposes. She is admired by her creativity, her boldness and for following her heart."
        },
        3: {
            "name": "Maria Montessori",
            "content": "Medical doctor and teacher. Maria Montessori was the first female doctor in Italy. She was interested in the rights of women and children, and dedicated her whole life to them. Maria worked with children with learning disadvantatges and functional diversity. She believed that all children were born with some potential that adults should help them to discover, regardless of their origins. These ideas were very groundbreaking for that time, so Maria had to put lots of effort to change the people's mind.\nMaria Montesori founded the school {i}Casa dei bambini{/i}, where children were treated with due dignity, so she taught them to care themselves, to blow their own noses and to fasten their coats' buttons. Moreover, she wrote {i}The Montessori Method{/i}, in which she presented her ideas to build a space where children could explore and learn their own way and the teachers would be their companions.\nShe pioneered in educative thinking. Maria spread her ideas around the world about mainstream education and education for children with special needs, which changed the vision and comprehension about infancy. She was three times nominated for the Nobel Peace Prize before she passed away."
        },
        4: {
            "name": "Wangari Maathai",
            "content": "Environmental activist. Wangari Muta Maathai, passionated about nature since very young, was the first woman to get a doctorate degree in eastern and central Africa. But she aimed to accomplish a greater change.\nIn that time, Kenya was suffering from deforestation and malnutrition. A great idea came to Wangari's mind, known as The Green Belt Movement: any people can change the world by saving one tree each time. This way, since 1977 the idea helped many local communities to plant over fifty million trees in Kenya and got their government to further protect the environment by making sure agriculture doesn't destroy forests and educating people to reduce, reuse and recycle.\nFurthermore, as a pioneer in education, she considered that only through education there could be a solution for the AIDS outbreak in Africa. So she wrote four books about ecology and Africa and founded the Wangari Maathai Institute for Peace and Environmental Studies.\nIn 2004, she was awarded the Nobel Peace Prize, becoming the first african woman to win it. She dedicated her life to help women and to improve the environment, which she wished to be preserved and protected so everybody could live in peace and harmony."
        },
        5: {
            "name": "Hedy Lamarr",
            "content": "Gifted actress and inventor. Trained in acting, she was highlighted in {i}Ecstasy{/i}, polemic movie were she was portrayed naked during the representation of an orgasm. For this reason, she was obliged to marry Fritz Mandl who forced her to join his work meetings, but she took advantage of that to learn about the state-of-the-art nazi weapon technology. Nevertheless, time afterwards she managed to flee to the United States where, even with some bad movies, she became a cinema star in the 30s.\nHedy knew the nazi practices and decided to help the allies during World War II. In 1942 she registered a patent for a method of transmission encoding, frequency-hopping spread spectrum, used by modern wireless technologies.\nShe never earned any money from the patent, which expired without being used and acknowledgement came very late. Her personal life wasn't very fortunate and her cinematographic career was in decline, which drove her to an obsession with pills and plastic surgery. In Austria, every November 9th it is celebrated the Inventor's Day in her honor."
        }
    }
