
## Dictionary in Catalan for all items of gallery.


init -10 python:
    gallery_dict_ca = {
        0: {
            "name": "Ada Lovelace",
            "content": "Primera programadora informàtica. Ada Lovelace estava fascinada per les màquines. Als 17 anys, va conèixer a Charles Babbage, el dissenyador de la {i}màquina diferencial{/i}, el primer ordinador de la història que podia fer càlculs amb nombres.\nImpressionada pels invents, s'interessà per la {i}màquina analítica{/i}, un dispositiu que podria assolir càlculs matemàtics més complexos. Ella va tenir la idea revolucionària de què la {i}màquina analítica{/i} tractés nombres, lletres i símbols mitjançant una sèrie d’instruccions, conegudes com a algoritmes. A més a més, va idear un sistema per repetir una seqüència d’operacions, conegut com a bucle ({i}looping{/i}).\nMalauradament, no va viure suficient per veure fer-se realitat les seves idees. Va morir als 36 anys, pobra i malalta. No va ser fins quasi un segle després que Alan Mathison Turing li reconegué la seva genialitat quan treballava amb els primers ordinadors moderns. És considerada {i}profeta de l’era informàtica{/i} per la seva perspectiva visionària sobre moltes de les funcionalitats dels ordinadors."
        },
        1: {
            "name": "Maria Montessori",
            "content": "Metgessa i professora que revolucionà l’educació. Brillant i amant de les matemàtiques, desitjà estudiar medicina i així es convertí en la primera metgessa d’Itàlia. Estava interessada en els drets de les dones i dels nens, i dedicà pràcticament tota la seva vida a tractar amb ells. Maria treballà amb nens amb problemes d’aprenentatge i diversitat funcional. Creia que tots els infants neixen amb potencial que els adults han d’ajudar-los a descobrir, ja que són aquestes aptituds les que els fan únics. No importa l’entorn originari dels nens, sinó que tots poden ser iguals en intel·ligència. Aquestes idees eren molt novedoses per l’època, amb la qual cosa Maria s’havia d’esforçar molt per canviar la mentalitat de la gent.\nMaria Montesori va crear l’escola {i}Casa dei bambini{/i}, en el qual es tractava els infants amb la dignitat que mereixien, per aquest motiu els ensenyà a cuidar-se, a mocar-se i a fer-se els botons dels abrics ells sols. A més a més, escrigué {i}El método Montessori{/i}, en el qual exposava les seves idees per crear un entorn en què els infants poguessin explorar i aprendre al seu propi ritme, i on els professors els acompanyessin.\nElla es convertí en pionera del pensament educatiu. Compartí les seves idees arreu del món sobre l’educació convencional i l’educació per infants amb necessitats especials, la qual cosa va canviar la visió i comprehensió que es tenia de la infància. Fou nominada tres vegades al Premi Nobel de la Pau abans de morir."
        },
        2: {
            "name": "Frida Kahlo",
            "content": "Pionera de la pintura mexicana i heroïna feminista. Als 18 anys, Frida Kahlo va patir un accident de trànsit, en el qual gairebé perd la vida. Els mesos de recuperació foren durs, els passà al llit, plena d’avorriment i tristesa. Va ser en aquell moment que decidí iniciar-se en la pintura.\nQuan es trobà millor, va emparellar-se amb en Diego Rivera, amb qui no va poder tenir fills a causa de les lesions de l’accident. Aquesta gran tristesa va ser inspiració per molts dels seus quadres, igual que algunes de les seves mascotes.\nLes seves obres eren molt personals, 55 de les seves 143 pintures són autoretrats. Per costum, es dibuixava amb duresa i poc atractiva, celles espesses i bigoti.\nMentre ella es feia famosa, la seva salut empitjorà. Va morir als 47 anys. Avui dia, és un exemple a seguir perquè va demostrar que les dones, malgrat els obstacles, poden fer tot el que es proposin. És admirada per la seva creativitat, la seva audàcia i per seguir el seu cor."
        },
        3: {
            "name": "Marie Curie",
            "content": "Eminent científica. Malgrat va poder anar a la universitat, la seva vida fou molt pobra i gens fàcil, fins que va conèixer a Pièrre Curie, amb qui va formar una família. Ambdós treballaren plegats per investigar la radioactivitat, varen descobrir el poloni i el radi. Al 1903, aconseguiren el Premi Nobel, i Marie es convertí en la primera dona en guanyar-ne un, tot i que vuit anys més tard aconseguí el de Química. Després de la mort accidentada de Pière, el substituí i es convertí en la primera professora de la Universitat de la Sorbona. A més a més, Marie contribuí a desenvolupar màquines portàtils de raigs X per dur-les en ambulàncies, les {i}petites curies{/i}. A part de ser-ne la conductora, va formar a metges i ajudants per ensenyar-los a usar l’equip.\nMolts dels homes amb qui va treballar la tractaren molt malament i li pagaren molt poc, de manera que seguia tenint una vida molt pobra. Ignorant la seva perillositat, la companyia de tubs d'assaig plens de material radioactiu va fer emmalaltir-la i morí temps més tard.\nAvui dia, l'equip se segueix usant en la medicina i gràcies a elles milions de persones han pogut ser tractades i curades. Marie Curie fou una de les millors científiques de la història."
        },
        4: {
            "name": "Wangai Maathai",
            "content": "Activista pel medi ambient. Wangari Muta Maathai, apassionada des de ben petita per la naturalesa, fou la primera dona d’Àfrica oriental i central en doctorar-se en una universitat. Però ella aspirava a realitzar un canvi encara més gran.\nPer aquell temps, Kènia estava patint problemes a causa de la deforestació i la malnutrició. A Wangari se li va ocórrer una idea genial, coneguda com el Moviment Cinturó Verd: qualsevol persona pot canviar el món salvant un arbre cada vegada. D’aquesta manera, a partir de 1977, aquesta idea va ajudar a diferents comunitats locals a plantar més de cinquanta-un milions d’arbres a Kènia i va aconseguir que el govern protegís més el medi ambient, fent que l’agricultura no destrueixi els boscos i ensenyant als habitants a reduir, reusar i reciclar.\nA més a més, com a pionera en l’educació, considerava que solament a través de l’educació podria trobar-se una solució per l'extensió del SIDA a l’Àfrica. Així, escrigué quatre llibres sobre ecologia i Àfrica, i fundà l’Institut Wangari Maathai per la Pau i els Estudis Medi Ambientals.\nAl 2004, va rebre el Premi Nobel de la Pau, convertint-se en la primera dona africana en guanyar-lo. Ella va dedicar la seva vida a ajudar les dones i a millorar el medi ambient, el qual desitjava que es preservés i es protegís per a què tothom pogués viure en pau i harmonia."
        },
        5: {
            "name": "Hedy Lamarr",
            "content": "Inventora i actriu superdotada. Formada en interpretació, començà destacant en {i}Ecstasy{/i}, pel·lícula polèmica en la qual es mostrava nua i el seu rostre durant un orgasme. Per aquest motiu, l’obligaren a casar-se amb Fritz Mandl, qui la forçava a assistir a les seves reunions de feina però ella aprofitava per aprendre sobre l’última tecnologia armamentística nazi. No obstant això, més tard aconseguí fugir als Estats Units, i malgrat les pel·lícules interpretades fossin un desastre, es convertí en l'estrella dels anys 30.\nHedy coneixia les pràctiques nazis i decidí ajudar els aliats en la Segona Guerra Mundial. L’any 1942, va inscriure la patent d’un mètode de codificació de transmissions, l’espectre eixamplat per salt de freqüències, mètode usat per les actuals tecnologies sense fil.\nElla no aconseguí mai diners per la patent, que caducà sense ser usada, i el reconeixement va tardar en arribar. La seva vida personal no fou afortunada i la seva carrera cinematogràfica patí un fort descens, que la dugué a l'obsessió per la cirugia estètica i el món de les pastilles. A Àustria, el dia 9 de novembre se celebra el Dia de l’Inventor en honor seu."
        }
    }
