
## Dictionary in Spanish for all items of glossary.


init -10 python:
    glossary_dict_es = {
        0: {
            "name": "Adrienne Rich",
            "content": "{i}Compulsory Heterosexuality and Lesbian Existence{/i} (1980), ensayo escrito por Adrienne Rich, establece la heterosexualidad obligatoria como un mecanismo capitalista para imponer la subordinación económica de la mujer al hombre en el matrimonio y la maternidad. La explotación y el abuso patriarcal han provocado, escribe, que las mujeres interioricen la idea de que son objetos sexuales y que acepten la violación de sus límites por parte de los hombres para sobrevivir. Así, propone una mujer que se identifique como mujer y que esta a su vez quiera a las demás mujeres, lo que llama un {i}lesbianismo contínuo{/i}."
        },
        1: {
            "name": "Aleksandra Kollontay",
            "content": "Aleksandra Kollontay fue defensora de una sociedad estructurada y más justa, cuyo Estado ayudara a las mujeres, en particular a las madres trabajadoras, y estas tuvieran derechos políticos y legales igual que los hombres. En 1909, escribe {i}Los fundamentos sociales de la cuestión femenina{/i} ({i}The Social Basis of the Woman Question{/i}), cuya obra propone medidas como ayudas económicas estatales a embarazadas y lactantes, la socialización del trabajo doméstico y el cuidado de los infantes, responsabilidad que considera social y no individual, ya que esto permitiría a las mujeres contribuir en el Estado política y económicamente."
        },
        2: {
            "name": "Alicia Walker",
            "content": "Según Alicia Walker, el feminismo dominado por mujeres blancas de clase media ignora el racismo y a su vez contribuye a él. Las mujeres negras, además de la desigualdad de género, sufren la racial y, por lo tanto, están más oprimidas. Por este motivo, establece que ellas requieren de un feminismo propio, que llama {i}womanism{/i} (1983), que considere la opresión de género, racial y de clase. En este sentido, el {i}womanism{/i} aspira a bregar la vida entera de las mujeres negras y contribuyendo a las maneras en que sobreviven a sus múltiples opresiones. En este abanico de acciones, pone énfasis en las mujeres {i}womanish{/i}, aquellas que se cuestionan, en el amor hacia otras mujeres y otros seres, y en el autocuidado, a través de la cultivación del amor a la espiritualidad, el baile y la música. En este sentido, el {i}womanism{/i} apuesta por la renúncia a las divisiones de clase, la promoción de la igualdad de género, la libertad de sexualidad y por el rechazo del racismo."
        },
        3: {
            "name": "Angela Davis",
            "content": "El año 1981, se publicó {i}Women, Race and Class{/i}, de Angela Davis. Este estudio muestra que el feminismo está plagado de prejuicios de raza y clase. Asimismo, también menciona como la institución de la esclavitud sometió a la mujer negra a un trato infrahumano que reflejaba supuestos muy diferentes sobre feminidad, raza y clase. De esta forma, expone las causas por las cuales las reivindicaciones de las mujeres negras fueron sistemáticamente invisibilizadas a pesar del potencial revolucionario que escondían. Además de poner de manifiesto las estrategias de lucha de las mujeres negras, también expone los problemas de composición de las diferencias que aún hoy en día siguen estropeando los movimientos políticos."
        },
        4: {
            "name": "Anne Koedt",
            "content": "Los hombres llamaban {i}frígidas{/i} a las mujeres que no tenían orgasmos vaginales. Es tan así que las mujeres se definen sexualmente según aquello que complace al hombre, es decir, la sexualidad es política. Anne Koedt, autora de {i}The Myth of the Vaginal Orgasm{/i} (1968), expone que no es suficiente con la estimulación vaginal por sí misma porqué no estimula el clítoris; luego, no hay orgasmo. El hecho de que los hombres llamen {i}frígidas{/i} a las mujeres las culpabiliza. De esta forma, los hombres mantienen el mito del orgasmo vaginal por el deseo predominante de penetración que tienen y, a su vez, por miedo a ser prescindibles."
        },
        5: {
            "name": "Betty Friedan",
            "content": "Betty Friedan desde un enfoque psicosocial de la manera de vivir de las mujeres, descifra el rol opresivo y asfixiante que tienen impuesto y analiza su malestar y descontento. El problema principal es político, ya que el concepto de mujer se equivale a madre y mujer, lo cual anula toda posibilidad de realización personal y culpabiliza a todas aquellas que no son felices viviendo solamente para el resto. Esta sensación de infelicidad de las mujeres la llama {i}el problema que no tiene nombre{/i}. La imagen idealizada de la feminidad arraigada en el matrimonio y la família seguía presente en las mujeres, que la autora mencionó en su libro {i}The Feminine Mystique{/i} (1963). A las anteriores razones del malestar de las mujeres, se suman su infantilización, los cursos de género en las escuelas, su renúncia a una carrera professional, y la atribución a ellas de una función sexual y biológica. Como rutas de escape, propone la formación y el trabajo remunerado."
        },
        6: {
            "name": "Catherina Ahlgren",
            "content": "Catherina Ahlgren, amiga de Charlotta Nordenflycht, en el año 1772 publicó una serie de cartas retóricas, dirigidas a hombres y mujeres, con el pseudónimo {i}Adelaide{/i}, en las cuales hablaba de amistad, consideraciones morales y del amor verdadero, concepto únicamente existente cuando un hombre y una mujer se tratan como iguales. Además, era defensora del activismo social, la democracia, la igualdad de género y la solidaridad de las mujeres con respecto a la dominación masculina. El año 1782, fue editora de {i}Del Arte para Complacer Correctamente{/i} ({i}Om att rätt behaga{/i}), uno de los primeros periódicos finlandeses."
        },
        7: {
            "name": "Clara Campoamor",
            "content": "Clara Campoamor empezó a interesarse por los derechos de las mujeres cuando trabajaba en el periódico {i}La Tribuna{/i}. Motivada cada vez más por una mayor curiosidad política, llegó a ser la primera mujer miembro del Tribunal Supremo de España. En 1931, formó parte del equipo encargado de elaborar la Constitución de la nueva República, y fue gracias a ella que se incluyó el sufragio universal. Con la llegada de la dictadura de Franco, éste y muchos otros avances quedaron cancelados. Clara Campoamor se exilió cuando empezó la Guerra Civil Española, y el general Franco no la dejó volver nunca."
        },
        8: {
            "name": "{i}Consciousness-Raising{/i}",
            "content": "El año 1967 surgió el concepto de {i}concienciación{/i} relativa a la tarea principal de las feministas: despertar una conciencia de clase entre las mujeres. De esta manera, uno de los métodos para difundir la causa del movimiento de liberación de la mujer fue el {i}consciousness-raising{/i}. Este método, que ayudaba a mejorar la autoestima de las mujeres al ser reconocidas como una entidad propia, consistía en reunirse para hablar de sus experiencias, desde la infancia hasta el matrimonio y la sexualidad, con el objetivo de demostrar que las dificultades personales se arraigaban a cuestiones políticas que se tenían que cambiar; {i}lo personal es político{/i}. No solamente era necesario transformar el espacio público, sino también el privado. Las relaciones de poder que estructuran la família y la sexualidad eran centros de dominación de las mujeres, mientras que los hombres recibían beneficios económicos, sexuales y psicológicos del sistema patriarcal."
        },
        9: {
            "name": "{i}Convención de Seneca Falls{/i}",
            "content": "La {i}Declaración de Sentimientos y Resoluciones{/i} se firmó en la {i}Convención de Seneca Falls{/i} (19 julio 1848), cuyo ímpeto procedía del activismo política contra la esclavitud, pretendía combatir la falta de derechos sociales, civiles y religiosos de las mujeres. Lucretia Mott fue la primera presidenta de l'{i}Asociación Americana por la Igualdad de Derechos{/i} (AERA), que buscaba el sufragio universal. Años más tarde, se divide por la decisión de priorizar el sufragio masculino afroamericano en la {i}Asociación Nacional pro Sufragio de las Mujeres{/i} (NWSA), de la cual forman parte Elizabeth C. Stanton y Susan B. Anthony, y que lucha por el sufragio femenino a nivel federal, y en la {i}Asociación Americana pro Sufragio de la Mujer{/i} (AWSA), de la cual forman parte Charlotte Woodward Pierce y Lucy Stone, y que lucha por el sufragio universal a nivel estatal. En 1890, ambas formaron la {i}Asociación Nacional Americana pro Sufragio de la Mujer{/i} (NAWSA). Charlotte Woodward fue la única firmante que vivió la 19a Enmienda en 1920, aunque la enfermedad le impidiera votar."
        },
        10: {
            "name": "{i}Coverture{/i}",
            "content": "La ley {i}coverture{/i} establece que los derechos de la mujer pasan al marido cuando se casa, así como sus propiedades, pertenencias, dinero y herencias. Además, el marido tiene amparo legal para privar de libertat y maltratar a la mujer con el fin de asegurar su cumplimiento de los deberes domésticos y sexuales, y dispone de la custodia exclusiva de sus hijos. El divorcio requería una ley privada del Parlamento y era excepcional y, aunque la separación fuera legal, era cara y el marido podía demandar por {i}conversación criminal{/i} los amantes sexuales sospechosos de su mujer. Para las mujeres, solamente se contemplaban la crueldad grave, el incesto y la bigamia como causas de divorcio. Sólo cuatro mujeres pidieron el divorcio entre 1765 y 1857."
        },
        11: {
            "name": "Elizabeth Montagu y las {i}Bluestockings{/i}",
            "content": "Elizabeth Montagu, de apodo {i}Queen of the Blues{/i}, fue la anfitriona del salón más prestigioso de Mayfair (Londres), cuya duración fue de cincuenta años. El año 1750, Elizabeth Vesey y ella fundaron la {i}Blue Stockings Society{/i}, nombre que referenciaba a la preferencia masculina por las medias de lana azules, en lugar de las de seda negras de uso ordinario y que permetían simbolizar la informadidad relativa de las reuniones. Estas mujeres acogían a hombres y mujeres con el objetivo de promover la {i}conversación racional{/i} de la cual posteriormente se pudiera extraer el progreso moral. Los objetivos de las {i}Bluestockings{/i} pasaban por promover el debate sobre literatura y artes, ofrecer un espacio donde hombres y mujeres pudieran dialogar como iguales, procurar apoyo mútuo a las mujeres que quisieran escribir y publicar, así como promover reuniones sociales en las cuales el estímulo de la conversación fuera el sustitutivo del juego y el alcohol."
        },
        12: {
            "name": "Emma Goldman",
            "content": "Emma Goldman fue la precursora del anarcofeminismo, cuyas raíces ideológicas se remontan a los movimientos obreros de finales del siglo XIX y principios del XX. Su anarquismo feminista proponía combatir las relaciones de explotación entre patronos y trabajadores, entre gobierno / fuerzas armadas y la población civil, y también la sumisión impuesta históricamente a las mujeres por el patriarcado capitalista. Además, defendió una mayor libertad en las relaciones sexuales, así como la ayuda para las madres trabajadoras y la prevención del embarazo."
        },
        13: {
            "name": "Germaine Greer",
            "content": "El año 1970, se publicó {i}The Female Eunuch{/i}, de Germaine Greer. Menciona que las mujeres están castradas social, sexual y culturalmente. Pone énfasis en que ellas tienen que aprender a cuestionar la {i}normalidad{/i} femenina, ya que establece que las cualidades más valoradas en una mujer son las del eunuco: timidez, languidez y delicadeza. No sólo eso, sino que a las mujeres se las condiciona mediante el uso de estereotipos para evitar pensar por sí mismas, para no comportarse de manera independiente y para verse a sí mismas ilógicas, subjetivas y tontas. Hasta el amor ha sido pervertido por mitos románticos y por la pornografía. Critica la família nuclear por ser perjudicial; amar resulta ser símbolo de odio, asco y aversión. Finalmente, establece que no se tendría que mantener relaciones patriarcales, sino que las mujeres se tienen que abrir hacia la liberación social y sexual."
        },
        14: {
            "name": "Harriet Taylor Mill y John Stuart Mill",
            "content": "Harriet Taylor Mill fue una activista que exigía igualdad con los hombres en todos los derechos (políticos, civiles y sociales), tal como lo describe en el ensayo {i}La Emancipación de las Mujeres{/i} ({i}The Enfranchisement of Women{/i}, 1851). Además, cree que contribuir en los ingresos familiares haría que la mujer fuera más respetada por su marido, que la vería como una socia y no como una sirvienta doméstica. Junto con su marido, John Stuart Mill, escribió {i}Los primeros ensayos sobre el matrimonio y el divorcio{/i} ({i}Early Essays on Marriage and Divorce{/i}) en 1832, en los cuales indagan en una nueva manera de entender y vivir en pareja, que no suponga la esclavitud de la mujer, sino un contrato entre iguales, ya que ambos consideraban que las mujeres eran individuos libres y que tenían que gozar de independencia económica."
        },
        15: {
            "name": "Hedvig Charlotta Nordenflycht",
            "content": "Hedvig Charlotta Nordenflycht, escritora y pensadora sueca, debutó literariamente en el año 1742 con {i}El lamento de la mujer sueca{/i} ({i}Den sörjande Turturduvan{/i}), en cuya obra reclamaba mayores derechos para su sexo. Tras unos cuantos años, en 1753 fue la primera mujer adminitda en la {i}Tankebyggararorden{/i} ({i}Orden de los constructores del pensamiento{/i}), una agrupación literaria en la ciudad de Estocolmo que aspiraba a la reforma de la literatura sueca. Con obras como {i}El deber de las mujeres de usar el ingenio{/i} ({i}Fruentimbers Plikt att upöfwa deras Wett{/i}, 1744) para defender el intelecto femenino o {i}La Defensa de las mujeres{/i} ({i}Fruntimrens försvar{/i}, 1761) per refutar la misoginia, reivindicó el derecho a ser intelectualmente activa. Ella firmaba sus obras con su verdadero nombre."
        },
        16: {
            "name": "Kimberlé Crenshaw",
            "content": "Especialista en teoría crítica de la raza, Kimberlé Crenshaw definió el término {i}intersectionality{/i}. En el ensayo de 1991, {i}Mapping the Margins: Intersectionality, Identity Polotics and Violence against Women of Color{/i}, la dividió en tres tipos. La interseccionalidad estructural se refiere a la diferencia en la opresión ejercida sobre mujeres blancas y sobre mujeres negras. La interseccionalidad política es relativa al impacto de las leyes y políticas públicas sobre las mujeres de color, independientemente de si están inspiradas en motivaciones feministas o antirracistas. Y, finalmente, la interseccionalidad representacional se refiere a cómo son representadas las mujeres de color en la cultura popular y en cómo afecta ello en su vida cuotidiana. De esta manera, establece que la multiplicidad de la opresión no tiene que tener un enfoque aditivo, sino que se tiene que comprender como la raza complica la opresión de clase, el género la opresión racial, y así sucesivamente."
        },
        17: {
            "name": "{i}La Liberté guidant le peuple{/i}",
            "content": "El cuadro de {i}La Libertad guiando al pueblo{/i} ({i}La Liberté guidant le peuple{/i}) fue pintado por Eugène Delacroix para representar la libertad como una guía que conduce al pueblo, constituido por miembros de clase social media y baja durante el día 28 de julio de la Revolución de las {i}Tres Gloriosas{/i} ({i}Trois Glorieuses{/i}). En este sentido, el concepto de libertad es una alegoría representada como una mujer dotada de mucha belleza."
        },
        18: {
            "name": "{i}La Tribune des femmes{/i}",
            "content": "{i}La Tribune des femmes{/i} fue la primera revista feminista de clase obrera que difundía los sansimonianos e invitaba a las mujeres, de cualquier clase social, a contribuir en su progreso social. De esta manera, se proponía una alianza entre mujeres proletarias y privilegiadas, con el fin de crear una {i}nueva mujer{/i}, ya que la opresión vincula a todas las mujeres por igual, al margen de su categoría social. Este hecho constituyó el primer intento de crear una conciencia femenina."
        },
        19: {
            "name": "{i}Ladies National Association{/i}",
            "content": "En 1869, Josephine Butler fundó la {i}Asociación Nacional de Damas para derogar las Leyes de Enfermedades Contagiosas{/i} ({i}Ladies National Association for the Repeal of the Contagious Diseases Acts{/i}), las cuales pretendían controlar la propagación de las enfermedades venéreas entre las fuerzas armadas autorizando reconocimientos médicos forzosos a las prostitutas. Argumentaba que eran injustas y que evidenciaban la doble moral sexual, ya que castigaban a las víctimas, las mujeres, de la explotación masculina, mientras que los perpetradores, los hombres, quedaban impunes. Además, exponían un prejuicio de clase, ya que protegían a los hombres de clase media y alta, y perseguían a las mujeres de clase trabajadora, lo cual provocaba que las prostitutas fueran una clase esclava destinada a complacer a los hombres."
        },
        20: {
            "name": "{i}Langham Place Group{/i}",
            "content": "Las {i}Damas de Langham Place{/i} ({i}Langham Place Group{/i}) fue el primer grupo activista feminista del Reino Unido. Eran mujeres instruidas de clase mediana que formularon peticiones para reformar las leyes relativas a las mujeres casadas. En parte gracias a este activismo, se aprobó la {i}Ley de Causas Matrimoniales{/i} ({i}Matrimonial Causes Act{/i}) en 1857, que trajo la creación del primer tribunal de divorcios a Gran Bretaña, siendo el primer paso para desmantelar la {i}ley coverture{/i}. En 1859, las Damas se trasladaron al 19 de Langham Place, domicilio de {i}The English Woman’s Journal{/i}. Años más tarde, hicieron campaña para el sufragio femenino, que trajo la aprobación en 1870 de la {i}Ley de Propiedad de las Mujeres Casadas{/i} ({i}Married Women’s Property Act{/i}), en la cual ellas tenían el derecho a conservar sus propias ganancias, ingresos por renta e inversión, y herencias inferiores a dos cientas libras. No obstante, la situación no cambió hasta la ampliación de la ley en 1882."
        },
        21: {
            "name": "Margaret Sanger",
            "content": "Hasta que Margaret Sanger no vinculó la emancipación de la mujer con el control de la natalidad, muchas otras feministas eran contrarias a la contracepción, ya que la consideraban una práctica corruptora que animaría a las mujeres a ser sexualmente más activas y daría a los hombres una libertad sexual sin límites dentro y fuera del matrimonio. Desafiando la {i}Ley Comstock{/i} ({i}Comstock laws{/i}), que calificaba como inmoral la difusión de información sobre métodos anticonceptivos, escribió artículos explícitos sobre sexo y contracepción para mujeres, y realizó giras de conferencias a las cuales asistieron a menudo mujeres de clase trabajadora. La iglésia católica se opuso al uso de estos métodos y, aunque en la década de 1930 empezara a ser socialmente más aceptado, sólo lo era para las mujeres casadas. No fue hasta 1960 con el movimiento de demanda de derechos reproductivos que las mujeres solteras pudieron usarlos también."
        },
        22: {
            "name": "Mary Astell",
            "content": "Mary Astell destacó en el Reino Unido por defender en sus obras que las mujeres eran tan capaces de un pensamiento crítico y claro como los hombres, y que la aparente inferioridad era causada por el control masculino y el limitado acceso a la educación de las mujeres. Se enfrentó a la postura eclesiástica que consideraba el papel secundario de la mujer como un hecho de disposición divina, argumentando que Diós había creado la mujer con un alma igualmente inteligente y dotada de pensamiento. El año 1694 escribe {i}Una Propuesta Seria para Mujeres{/i} ({i}A Serious Proposal to the Ladies{/i}), obra en la cual instaba a las mujeres a aprender a desarrollar su intelecto y habilidades, y a no delegar siempre en los hombres."
        },
        23: {
            "name": "Mary Wollstonecraft",
            "content": "En el año 1792, Mary Wollstonecraft escribió {i}Vindicación de los derechos de la mujer{/i} ({i}A Vindication of the Rights of Woman{/i}) como reivindicación por la emancipación femenina en el ámbito doméstico. Insiste en la importancia de la educación, afirmando que, desde la infancia, a las niñas se las enseña a vivir subordinadas y con el sentimiento de inferioridad. Exponiendo {i}una revolución de los modales femeninos{/i}, describe el empoderamiento de las mujeres como una herramienta para poder dejar de ser dependientes de la aprobación masculina y poder acceder al ámbito público, ya que una vida limitada y restringida solamente al ámbito doméstico acababa por perjudicarlas psicológicamente. Pone énfasis en la cultivación personal e intelectual de la mujer, más allá de los estereotipos de género y de la apariencia física. De esta manera, cree en una educación igualitaria para hombres y mujeres, y propone la coeducación."
        },
        24: {
            "name": "Marxismo y feminismo",
            "content": "En el {i}Manifiesto comunista{/i} ({i}Manifest der Kommunistischen Partei{/i}) de 1848, Karl Marx y Friedrich Engels afirman que el capitalosmo oprime a las mujeres, tratándolas como ciudadanas subordinadas de segunda clase, tanto en família como en sociedad; la mujer es un simple instrumento de producción. En cambio, las feministas marxistas creían que en una sociedad capitalista las mujeres servían como reservistas del trabajo, a quienes se recurre cuando existe esa necesidad y a quienes se excluía cuando ésta desaparecía. Identifican el capitalismo y el patriarcado como el sistema dual subyacente a la opresión de las mujeres. Mujeres socialistas y comunistas, teóricas líderes del movimiento comunista internacional, maduraron cuestiones como el empoderamiento femenino y el sufragio universal, destacando Clara Zetkin y Rosa Luxemburg en Alemania y Aleksandra Kollontay en Rusia."
        },
        25: {
            "name": "{i}Mujeres Libres{/i}",
            "content": "{i}Mujeres Libres{/i} es uno de los grupos anarcofeministas más representativos. Se formó en España en 1936, al comienço de la Guerra Civil Española. Sus fundadoras eran miembros de la {i}Confederación Nacional del Trabajo{/i} (CNT). Las anarquistas luchaban por la revolución social, pero enfatizaban que ésta no se conseguiría mientras la CNT fuera mayormente masculina. El grupo exigió que la CNT tratara con urgencia la {i}cuestión femenina{/i}, que, aunque luchaba por la igualdad de género, rechazaba la etiqueta feminista porque consideraba el feminismo de la época demasiado burgués por no criticar ni el capitalismo ni el sistema de clases. {i}Mujeres Libres{/i} llevó a cabo dos estrategias: la captación, por atraer a mujeres a la lucha anarquista contra el capitalismo patriarcal gracias al cual siempre serían esclavizadas, y la captación, para ayudarlas a realizar su potencial."
        },
        26: {
            "name": "Nana Asma'u",
            "content": "Nana Asma’u, del califato de Sokoto, conocida por su posición como hija del califa y por su sabiduría, consideraba que la educación de las niñas tenía que ser institucionalizada. Por este motivo, creó una red de maestras itinerantes conocidas como {i}jajis{/i}, cuya misión era recorrer el imperio con el fin de instruir a las mujeres dentro de sus propias casas. Hoy en día, el legado de Asma'u aún está vigente con un conjunto de escuelas y organizaciones femeninas nigerianas que llevan su nombre y recuerdo. Así, su legado es un recordatorio de la educación para todo el mundo en el islam."
        },
        27: {
            "name": "Naomi Wolf",
            "content": "Naomi Wolf escribió {i}The Beauty Myth{/i} en 1990. Las normas de belleza impuestas por la sociedad patriarcal dicen a las mujeres que deben esforzarse para conseguir un ideal femenino imposible. Se esclavizan por su aspecto físico y se alejan de poder disfrutar de una vida plena y de la actividad feminista. Así, este mito impacta económicamente a las mujeres como individuos y a la sociedad capitalista en general; históricamente, porqué la convertía en mercancía, ya que su seguridad económica dependía de la medida en qué se adecuara al ideal, y ahora en su consumo de productos y servicios. De esta manera, el mito oprime a la mujer en el ámbito del trabajo, la cultura y la religión, el sexo y la alimentación, atrapándola mediante los cosméticos, la dieta, el ejercicio y la cirugía. La autora propone un futuro feminista en el cual el valor de las mujeres dependa de una definición propia de belleza. Las mujeres tienen que tener opciones y ser reconocidas como personas multidimensionales, respetadas por la sociedad como cabales y sexuales, y tener una vida rica y plena. No importa el aspecto para sentirse bella."
        },
        28: {
            "name": "Nawal El Saadawi",
            "content": "En 1972, Nawal El Saadawi escribió {i}Mujeres y sexo{/i}, cuya obra detalla todas las maneras en las cuales las mujeres egípcias eran oprimidas, entre ellas las prácticas de mutilación genital. Es médica y activista por los derechos de las mujeres de tendencia marxista, y fue prisionera en varias ocasiones. Ella rechazaba la interpretación masculina del islam, ya que creía que la liberación de las mujeres no tenía cabida en la teología islámica. Sus ideas se comprenden en la rama secular del feminismo en el mundo árabe, es decir, están inspiradas en ideas occidentales. En 1982 fundó la {i}Asociación Solidaria de Mujeres Árabes{/i} ({i}Arab Women Solidarity Association{/i})."
        },
        29: {
            "name": "{i}NOW 1966 Statement of Purpose{/i}",
            "content": "El año 1966 se fundó NOW, {i}National Organization of Women{/i}, organización basada en el principio de que todas las mujeres son, por encima de todo, seres humanos que tienen que tener la ocasión de desarrollar su potencial humano en toda su plenitud. Así, el objetivo de ésta es tomar medidas para que las mujeres participen en todos los ámbitos de la sociedad, ejerciendo todos sus privilegios y responsabilidades en una relación de igual a igual con los hombres. Desde su punto de vista, las mujeres pueden conseguir esta igualdad si son consideradas para la toma de decisiones en la vida política, social y económica norteamericana. De esta manera, sus miembros se organizan para iniciar o apoyar acciones con la finalidad de romper con los prejuicios y la discriminación contra las mujeres en cualquier ámbito importante en la sociedad norteamericana."
        },
        30: {
            "name": "Paula Gunn Allen",
            "content": "En {i}The Sacred Hoop: Recovering the Feminine in American Indian Traditions{/i} (1986), Paula Gunn Allen reivindica las ricas tradiciones matriarcales de las mujeres indígenas, que desarrollan en sus comunidades roles de liderazgo social, político y espiritual desde mucho antes que se produjera la colonización europea. Pone énfasis en la tradición de poder de las nativas americanas y señala que las ideas contemporáneas sobre el género están muy influenciadas por las nociones patriarcales de género introducidas por los colonos europeos."
        },
        31: {
            "name": "Olympe de Gouges",
            "content": "El año 1791, Olympe de Gouges, autora teatral y activista, redactó la {i}Declaración de los derechos de la mujer y de la ciudadanía{/i} ({i}La déclaration des droits de la femme et du citoyenne{/i}) con la finalidad de reivindicar derechos iguales para las mujeres. Este hecho sucedió después de que la {i}Declaración de los derechos del hombre y del ciudadano{/i} ({i}La déclaration des droits de l’homme et du citoyen{/i}) de 1789 afirmara los derechos y la libertad de todos los hombres. En su obra, de Gouges apeló a los valores de la Ilustración (los principios igualitarios y el individualismo) para exigir los mismos derechos para las mujeres. De esta manera, de Gouges fue detenida por criticar el gobierno y fue ejecutada en la guillotina en 1793 durante la época de Terror de la Revolución Francesa."
        },
        32: {
            "name": "{i}Riot Grrrl Manifesto{/i}",
            "content": "En 1991, se publicó el {i}Riot Grrrl Manifesto{/i} en el {i}Bikini Kill Zine 2{/i}, en el cual se establecían dieciséis razones del espíritu de {i}Riot Grrrl{/i} que responden al lema {i}Mujeres, sexo y rock and roll{/i}. Exigían poder compartir experiencias, estrategias y maneras de hacer con las otras mujeres, crear formas de ser no patriarcales y de hacer música, amigas y escenas basadas en la comunicación y la comprehensión en lugar de la competencia y las categorizaciones, exigen no querer vivir esclavizadas a los ideales del hombre ni a sus inseguridades, sino ser quién desean ser, establecen que las {i}riot grrrl{/i} buscan salvar la vida psicológica y cultural de todas las mujeres del mundo, exigen la promoción y la ayuda entre mujeres y artistas de todo tipo como parte integral del proceso, establecen su odio hacia el capitalismo en todas sus formas, y exigen poder validarse y fortalecerse dentro de la comunidad femenina haciendo, leyendo, viendo y escuchando. Y, por último, creen que las mujeres constituyen el alma de la fuerza revolucionaria que puede cambiar y cambiará el mundo de verdad."
        },
        33: {
            "name": "Shulamith Firestone",
            "content": "El año 1970, se publicó {i}The Dialectic of Sex{/i}, de Shulamith Firestone. Dice que querer resulta ser una relación de poder, y la desigualdad entre hombres y mujeres fundamento de todas las formas sociales de opresión, en las cuales se incluye la família nuclear. Reclama la crianza de los infantes con neutralidad de género, y propone la abolición de la família nuclear por parejas igualitarias no casadas y colectivos que crien juntos los infantes. Asimismo, considera que las mujeres tienen que tener más derechos y libertad de expresión. En conclusión, mencionó que el orígen de la opresión recae en la división sexual."
        },
        34: {
            "name": "Sojourner Truth",
            "content": "Sojourner Truth fue un símbolo para el feminismo antiesclavista y una figura fundamental para el movimiento abolicionista. Nació esclava pero consiguió huir en 1826. En la {i}Convención pro Derechos de las Mujeres{/i} de 1851, expuso un discurso memorable por la igualdad de las mujeres, en el cual se declaró igual a los hombres en fuerza e intelecto. Ya no sólo se reiteraba la demanda de sufragio femenino, sino que se enfatizaba en la igualdad frente a la ley sin distinción de sexo ni color, uniendo así la lucha por los derechos de las mujeres y la lucha por la libertad de los afroamericanos esclavizados en el movimiento abolicionista. En este caso, las mujeres eran doblemente discriminadas: por su condición de mujer y por su color de piel."
        },
        35: {
            "name": "Sophia Elisabet Brenner",
            "content": "Sophia Elisabet Brenner fue una de las primeras mujeres en reivindicar públicamente que hombres y mujeres merecían los mismos derechos. El año 1693 publicó el poema {i}La defensa justificada del sexo femenino{/i} ({i}Det Qwinliga Könetz rätmätige Förswar{/i}), en el cual mencionaba que la mujer era intelectualmente igual al hombre. Además, también defensaba en otras obras que hombres y mujeres eran iguales en todo menos en la apariencia física."
        },
        36: {
            "name": "Sufragismo",
            "content": "El movimiento sufragista fue una iniciativa de finales del siglo XIX y principios del XX. Las sufragistas, lideradas por Millicent Fawcett y constituyentes de la {i}Unión Nacional de Sociedades de Sufragio Femenino{/i} (NUWSS), de la cual casi todos sus miembros eran de clase media o alta, apostaban por una actividad no agresiva mediante peticiones pacíficas y mítines públicos. En cambio, las {i}suffragettes{/i}, lideradas por Emmeline Pankhurst y constituyentes de la {i}Unión Social y Política de las Mujeres {/i} (WSPU), de la cual algunos miembros buscan atraerse a la clase obrera, apuestan por la acción directa (violencia política) para conseguir publicidad con el lema {i}Hechos, no palabras{/i}. De esta manera, muchas de las {i}suffragettes{/i} fueron a prisión, alimentadas a la fuerza cuando allí realizaban huelgas de hambre, asesinadas, o perdieron la vida en la lucha por la causa. Destacan el caso de Emily de Emily Wilding Davison y el de Mary Richardson."
        },
        37: {
            "name": "Susan Faludi",
            "content": "En 1991, se publicó {i}Backlash: The Undeclared War Against American Women{/i}, de Susan Faludi. Identifica la {i}Nueva Derecha{/i} y su agenda profamília como motor de la reacción, que atribuye al miedo al éxito del feminismo. Critica la brecha salarial creciente y la hipocresía de los {i}emisarios de la reacción{/i} que impiden aprobar proyectos de ley para mejorar la asistencia infantil a la vez que culpaban a las madres trabajadoras de ser malas o las animaban a retomar los roles tradicionales. Pone énfasis en el rol de los medios de comunicación como estímulo de la reacción antifeminista, que asume la construcción de la imagen de la mujer trabajadora como insatisfecha y que difunde mitos sobre {i}la escasez de hombres{/i} o los {i}vientres estériles{/i}. En la moda y la cultura popular, se da paso a siluetas ceñidas y con ropa poco práctica, y en el cine se retrata a las profesionales solteras como mujeres desagradables o malvadas. Así mismo, comenta el pico de cosméticos y cirugía plástica debido a la presión de parecer joven, criticando también la psicología pop y los libros de autoayuda."
        },
        38: {
            "name": "Suzanne Voilquin",
            "content": "El año 1832, Suzanne Voilquin comenzó a trabajar como editora en la revista feminista de clase trabajadora {i}La Tribune des femmes{/i}. Ella decidió vivir de manera independiente, ya que quería ser un ejemplo para otras mujeres como una defensora de los valores sansimonianos, sobretodo después de la Revolución de 1830. El movimiento sansimoniano promovía un estilo de vida comunal, libre de la tiranía del matrimonio, en el cual los principios femeninos de la paz y la compasión sustituían los valores masculinos más agresivos."
        },
        39: {
            "name": "Virginia Woolf",
            "content": "En {i}Una habitación propia{/i} ({i}A Room of One’s Own{/i}, 1929), Virginia Woolf expuso las dificultades que tenían las escritoras para conseguir el mismo éxito que los hombres. Propone que las mujeres necesitan un espacio, que da nombre a la obra, para poder desarrollar su creatividad, libres de ataduras domésticas. Para ella, la independencia económica era necesaria para conseguirlo, siendo incluso más importante que el voto. Cuando tuvieran ese espacio para pensar, las mujeres podrían experimentar y desarrollar un lenguaje femenino absente hasta entonces en la literatura. Sugiere que las escritoras tienen que realizar una lucha interior contra el ideal femenino victoriano, ejemplificado en la mujer y madre perfecta."
        }
    }
