
## Dictionary in Catalan for all items of glossary.


init -10 python:
    glossary_dict_ca = {
        0: {
            "name": "Adrienne Rich",
            "content": "{i}Compulsory Heterosexuality and Lesbian Existence{/i} (1980), assaig escrit per Adrienne Rich, estableix l’heterosexualitat obligatòria com un mecanisme capitalista per imposar la subordinació econòmica de la dona a l’home en el matrimoni i la maternitat. L’explotació i l’abús patriarcal han provocat, escriu, que les dones interioritzin la idea de què són objectes sexuals i que acceptin la violació dels seus límits per part dels homes per sobreviure. Així, proposa una dona que s’identifiqui com a dona i que aquesta alhora estimi les altres dones, el que anomena un {i}lesbianisme continu{/i}."
        },
        1: {
            "name": "Aleksandra Kollontay",
            "content": "Aleksandra Kollontay va ser defensora d’una societat estructurada i més justa en la qual l’Estat recolzés a les dones, particularment a les mares treballadores, i aquestes tinguessin drets polítics i legals igual que els homes. L’any 1909, escriu {i}Els fonaments socials de la qüestió femenina{/i} ({i}The Social Basis of the Woman Question{/i}), obra en la qual proposa mesures com ajudes econòmiques estatals a embarassades i lactants, la socialització del treball domèstic i l’atenció als infants, la qual considera una responsabilitat social i no individual, ja que això permetria a les dones contribuir en l’Estat política i econòmicament."
        },
        2: {
            "name": "Alicia Walker",
            "content": "Segons Alicia Walker, el feminisme dominat per dones blanques de classe mitjana ignora el racisme i alhora contribueix a ell. Les dones negres, a més a més de la desigualtat de gènere, pateixen la racial i, per tant, estan més oprimides. Per aquest motiu, estableix que elles requereixen d’un feminisme propi, que anomena {i}womanism{/i} (1983), que consideri l’opressió de gènere, racial i de classe. En aquest sentit, el {i}womanism{/i} aspira a bregar la vida sencera de les dones negres i contribuïnt a les maneres en què sobreviuen a les seves múltiples opressions. Sota aquest ventall d’accions, fa èmfasi en les dones {i}womanish{/i}, aquelles que es qüestionen, en l’amor cap a altres dones i altres éssers, i en l’autocura, a través de la cultivació de l’amor a l’espiritualitat, el ball i la música. En aquest sentit, el {i}womanism{/i} aposta per la renúncia a les divisions de classe, la promoció de la igualtat de gènere, la llibertat de sexualitat i pel rebuig del racisme."
        },
        3: {
            "name": "Angela Davis",
            "content": "L’any 1981, es publicà {i}Women, Race and Class{/i}, d’Angela Davis. Aquest estudi mostra que el feminisme està plagat de prejudicis de raça i classe. Alhora, també esmenta com la institució de l’esclavitud va sotmetre a la dona negra a un tracte inhumà que reflectia supòsits molt diferents sobre feminitat, raça i classe. D’aquesta manera, exposa les causes per les quals les reivindicacions de les dones negres foren sistemàticament invisibilitzades tot i el potencial revolucionari que amagaven. A més a més de posar de manifest les estratègies de lluita de les dones negres, també exposa els problemes de composició de les diferències que encara avui dia segueixen esgarrant els moviments polítics."
        },
        4: {
            "name": "Anne Koedt",
            "content": "Els homes anomenaven {i}frígides{/i} a les dones que no tenien orgasmes vaginals. Tant és així que les dones es defineixen sexualment segons allò que complau a l’home, és a dir, la sexualitat és política. Anne Koedt, autora de {i}The Myth of the Vaginal Orgasm{/i} (1968), exposa que no és suficient l’estimulació vaginal per sí mateixa perquè no estimula el clítoris; llavors, no hi ha orgasme. El fet que els homes anomenin {i}frígides{/i} a les dones les culpabilitza. D’aquesta manera, els homes mantenen el mite de l’orgasme vaginal pel desig predominant de penetració que tenen i, alhora, per por a ser prescindibles."
        },
        5: {
            "name": "Betty Friedan",
            "content": "Betty Friedan des d’un enfocament psicosocial de la manera de viure de les dones, desxifra el rol opressiu i asfixiant que tenen imposat i analitza el seu malestar i descontentament. El problema principal és polític, ja que el concepte de dona s’equival a mare i muller, la qual cosa retalla tota possibilitat de realització personal i culpabilitza a totes aquelles que no són felices vivint solament per a la resta. Aquesta sensació d’infelicitat de les dones l’anomena {i}el problema que no té nom{/i}. La imatge idealitzada de la feminitat arrelada en el matrimoni i la família seguia present en les dones, que l’autora anomenà en el seu llibre {i}The Feminine Mystique{/i} (1963). A les anteriors raons del malestar de les dones, se sumen la seva infantilització, els cursos de gènere a les escoles, la seva renúncia a una carrera professional, i l’atribució a elles d’una funció sexual i biològica. Com a rutes d’escapament, proposa la formació i el treball remunerat."
        },
        6: {
            "name": "Catherina Ahlgren",
            "content": "Catherina Ahlgren, amiga de Charlotta Nordenflycht, l’any 1772 va publicar una sèrie de cartes retòriques, dirigides a homes i dones, amb el pseudònim {i}Adelaide{/i}, en les quals parlava d’amistat, consideracions morals i consells dirigits a les filles, i de l’amor veritable, concepte únicament existent quan un home i una dona es tracten com a iguals. A més a més, era defensora de l’activisme social, la democràcia, la igualtat de gènere i la solidaritat de les dones respecte de la dominació masculina. L’any 1782, va ser editora de {i}De l’Art per Complaure Correctament{/i} ({i}Om att rätt behaga{/i}), un dels primers diaris finlandesos."
        },
        7: {
            "name": "Clara Campoamor",
            "content": "Clara Campoamor va començar a interessar-se pels drets de les dones quan treballava al diari {i}La Tribuna{/i}. Motivada per cada vegada una major curiositat política, va arribar a ser la primera dona membre del Tribunal Suprem d’Espanya. L’any 1931, ella formà part de l’equip encarregat d’elaborar la Constitució de la nova República, i fou gràcies a ella que s’inclogué el sufragi universal. Amb l’arribada de la dictadura de Franco, aquest i molts altres avenços al respecte foren cancel·lats. Clara Campoamor s’exilià quan començà la Guerra Civil Espanyola, i el general Franco mai li va permetre tornar."
        },
        8: {
            "name": "{i}Consciousness-Raising{/i}",
            "content": "L’any 1967 sorgí el concepte de {i}conscienciació{/i} relativa a la tasca principal de les feministes: despertar una {i}consciència de classe{/i} entre les dones. D’aquesta manera, un dels mètodes per difondre la causa del moviment d’alliberació de la dona fou el {i}consciousness-raising{/i}. Aquest mètode, que ajudava a millorar l’autoestima de les dones al ser reconegudes com a entitat pròpia, consistia en reunir-se per parlar de les seves experiències, des de la infància fins el matrimoni i la sexualitat, amb l’objectiu de demostrar que les dificultats personals s’arrelaven a qüestions polítiques que s’havien de canviar; {i}allò personal és polític{/i}. No solament era necessari transformar l’espai públic, sinó també el privat. Les relacions de poder que estructuren la família i la sexualitat eren centres de dominació de les dones, mentre que els homes rebien beneficis econòmics, sexuals i psicològics del sistema patriarcal."
        },
        9: {
            "name": "{i}Convenció de Seneca Falls{/i}",
            "content": "La {i}Declaració de Sentiments i Resolucions{/i} se signà en la {i}Convenció de Seneca Falls{/i} (19 juliol 1848), l’ímpetu de la qual procedia de l’activisme polític contra l’esclavitud, pretenia combatre la falta de drets socials, civils i religiosos de les dones. Lucretia Mott fou la primera presidenta de l’{i}Associació Americana per la Igualtat de Drets{/i} (AERA), que recercava el sufragi universal. Anys més tard, es divideix per la decisió de prioritzar el sufragi masculí afroamericà en l’{i}Associació Nacional pro Sufragi de la Dona{/i} (NWSA), de la qual formen part Elizabeth C. Stanton i Susan B. Anthony, i que lluita pel sufragi femení a nivell federal, i en l’{i}Associació Americana pro Sufragi de la Dona{/i} (AWSA), de la qual formen part Charlotte Woodward Pierce i Lucy Stone, i que lluita pel sufragi universal a nivell estatal. Al 1890, ambdues formen l’{i}Associació Nacional Americana pro Sufragi de la Dona{/i} (NAWSA). Charlotte Woodward fou l’única signant que va viure la 19a Esmena l’any 1920, tot i que la malaltia li impedís votar."
        },
        10: {
            "name": "{i}Coverture{/i}",
            "content": "La llei {i}coverture{/i} estableix que els drets de la dona passen al marit quan es casa, així com les seves propietats, pertinences, diners i herències. A més a més, el marit té empara legal per privar de llibertat i maltractar la dona per tal d’assegurar el seu compliment dels deures domèstics i sexuals, i disposa de la custòdia exclusiva dels fills. El divorci requeria una llei privada del Parlament i era excepcional i, malgrat la separació fos legal, era cara i el marit podia demandar per {i}conversació criminal{/i} els amants sexuals sospitosos de la seva dona. Per a les dones, només es contemplaven la crueltat greu, l’incest i la bigàmia com a causes de divorci. Només quatre dones demanaren el divorci entre 1765 i 1857."
        },
        11: {
            "name": "Elizabeth Montagu i les {i}Bluestockings{/i}",
            "content": "Elizabeth Montagu, de sobrenom {i}Queen of the Blues{/i}, va ser l’amfitriona del saló més prestigiós de Mayfair (Londres), la duració del qual fou de cinquanta anys. L’any 1750, ella i Elizabeth Vesey varen fundar la {i}Blue Stockings Society{/i}, nom que feia referència a la preferència masculina per les mitges de llana blaves enlloc de les de seda negres d’ús quotidià i que permetien simbolitzar la informalitat relativa de les reunions. Aquestes dones acollien homes i dones amb l’objectiu de promoure la {i}conversa racional{/i} de la qual posteriorment es pogués extreure el progrés moral. Els objectius de les {i}Bluestockings{/i} passaven per promoure el debat sobre literatura i arts, oferir un espai on homes i dones poguessin dialogar com a iguals, procurar recolzament mutu a les dones que volguessin escriure i publicar, així com promoure reunions socials en les quals l’estímul de la conversa fos el substitutiu del joc i l’alcohol."
        },
        12: {
            "name": "Emma Goldman",
            "content": "Emma Goldman és la precursora de l’anarcofeminisme, les arrels ideològiques del qual es remunten als moviments obrers de finals del segle XIX i principis del XX. El seu anarquisme feminista proposava combatre les relacions d’explotació entre patrons i treballadors, entre govern / forces armades i la població civil, i també la submissió imposada històricament a les dones pel patriarcat capitalista. A més a més, va defensar una major llibertat en les relacions sexuals, així com l’ajuda per a mares treballadores i la prevenció de l’embaràs."
        },
        13: {
            "name": "Germaine Greer",
            "content": "L’any 1970, es va publicar {i}The Female Eunuch{/i}, de Germaine Greer. Menciona que les dones estan castrades social, sexual i culturalment. Fa èmfasi en què elles han d’aprendre a qüestionar la {i}normalitat{/i} femenina, ja que estableix que les qualitats més valorades en una dona són les de l’eunuc: timidesa, llanguiment i delicadesa. No només això, sinó que a les dones se les condiciona mitjançant l’ús d’estereotips per evitar pensar per sí mateixes, per no comportar-se de manera independent i per veure’s a sí mateixes il·lògiques, subjectives i ruques. Fins i tot, l’amor ha estat pervertit per mites romàntics i per la pornografia. Critica la família nuclear per ser perjudicial; estimar resulta ser símbol d’odi, fàstic i aversió. Finalment, estableix que no s’hauria de mantenir relacions patriarcals, sinó que les dones s’han d’obrir cap a l’alliberació social i sexual."
        },
        14: {
            "name": "Harriet Taylor Mill i John Stuart Mill",
            "content": "Harriet Taylor Mill fou una activista que exigia igualtat amb els homes en tots els drets (polítics, civils i socials), tal i com ho escriu en l’assaig {i}L’Emancipació de les Dones{/i} ({i}The Enfranchisement of Women{/i}, 1851). A més a més, creu que contribuir en els ingressos familiars faria que la dona fos més respetada pel seu marit, que la veuria com una sòcia i no com una serventa domèstica. Conjuntament amb el seu marit, en John Stuart Mill, va escriure {i}Els primers assajos sobre el matrimoni i el divorci{/i} ({i}Early Essays on Marriage and Divorce{/i}) l’any 1832, en els quals indaguen en una nova manera d’entendre i viure en parella que no suposi l’esclavitud de la dona, sinó un contracte entre iguals, ja que ambós consideraven que les dones eren individus lliures i que havien de tenir independència econòmica."
        },
        15: {
            "name": "Hedvig Charlotta Nordenflycht",
            "content": "Hedvig Charlotta Nordenflycht, escriptora i pensadora sueca, va debutar literàriament l’any 1742 amb {i}El lament de la dona sueca{/i} ({i}Den sörjande Turturduvan{/i}), en el qual reclamava majors drets pel seu sexe. Transcorreguts uns quants anys, en 1753 va ser la primera dona admesa en la {i}Tankebyggararorden{/i} ({i}Ordre dels constructors del pensament{/i}), una agrupació literària en la ciutat d’Estocolm que aspirava a la reforma de la literatura sueca. Amb obres com {i}El deure de les dones d’utilitzar l’enginy{/i} ({i}Fruentimbers Plikt att upöfwa deras Wett{/i}, 1744) per defensar l’intel·lecte femení o {i}La Defensa de les dones{/i} ({i}Fruntimrens försvar{/i}, 1761) per refutar la misogínia, va reivindicar el dret a ser intel·lectualment activa. Ella firmava les seves obres amb el seu nom vertader."
        },
        16: {
            "name": "Kimberlé Crenshaw",
            "content": "Especialista en teoria crítica de la raça, Kimberlé Crenshaw definí el terme {i}intersectionality{/i}. En l’assaig de 1991, {i}Mapping the Margins: Intersectionality, Identity Polotics and Violence against Women of Color{/i}, la dividí en tres tipus. La interseccionalitat estructural es refereix a la diferència en l’opressió exercida sobre dones blanques i sobre dones negres. La interseccionalitat política és relativa a l’impacte de les lleis i polítiques públiques sobre les dones de color, independentment de si són inspirades en motivacions feministes o antiracistes. I, finalment, la interseccionalitat representacional es refereix a com són representades les dones de color en la cultura popular i en com afecta això a la seva vida quotidiana. D’aquesta manera, estableix que la multiplicitat de l’opressió no ha de tenir un enfocament additiu, sinó que s’ha de comprendre com la raça complica l’opressió de classe, el gènere l’opressió racial, i així successivament."
        },
        17: {
            "name": "{i}La Liberté guidant le peuple{/i}",
            "content": "El quadre de {i}La Llibertat guiant el poble{/i} ({i}La Liberté guidant le peuple{/i}) va ser pintat per Eugène Delacroix per representar la llibertat com a guia que condueix el poble, constituït per membres de classe social mitjana i baixa durant el dia 28 de juliol de la Revolució de les {i}Tres Glorioses{/i} ({i}Trois Glorieuses{/i}). En aquest sentit, el concepte de llibertat és una al·legoria representada com una dona dotada de molta bellesa."
        },
        18: {
            "name": "{i}La Tribune des femmes{/i}",
            "content": "{i}La Tribune des femmes{/i} va ser la primera revista feminista de classe obrera que difonia els valors sansimonians i convidava a les dones, de qualsevol classe social, a contribuir al seu progrés social. D’aquesta manera, es proposava una aliança entre dones proletàries i privilegiades, amb la finalitat de crear una {i}nova dona{/i}, ja que l’opressió vincula a totes les dones per igual, al marge de la seva categoria social. Aquest fet va constituir el primer intent de crear una conciència femenina."
        },
        19: {
            "name": "{i}Ladies National Association{/i}",
            "content": "L’any 1869, Josephine Butler fundà l’{i}Associació Nacional de Dames per derogar les Lleis de Malalties Infeccioses{/i} ({i}Ladies National Association for the Repeal of the Contagious Diseases Acts{/i}), les quals pretenien controlar la propagació de malalties infeccioses entre les forces armades autoritzant reconeixements mèdics forçosos a les prostitutes. Argumentava que eren injustes i que evidenciaven la doble moral sexual, ja que castigaven a les víctimes, les dones, de l’explotació masculina, mentre que els perpetradors, els homes, quedaven impunes. A més a més, exposaven un prejudici de classe, ja que protegien els homes de classe mitjana i alta, i perseguien les dones de classe treballadora, la qual cosa feia que les prostitutes fossin una classe esclava destinada a complaure els homes."
        },
        20: {
            "name": "{i}Langham Place Group{/i}",
            "content": "Les {i}Dames de Langham Place{/i} ({i}Langham Place Group{/i}) fou el primer grup activista feminista del Regne Unit. Eren dones instruïdes de classe mitjana que formularen peticions per reformar les lleis relatives a les dones casades. Gràcies en part a aquest activisme, s’aprovà la {i}Llei de Causes Matrimonials{/i} ({i}Matrimonial Causes Act{/i}) l’any 1857, que portà a la creació del primer tribunal de divorcis a Gran Bretanya, sent el primer pas per ensorrar la {i}llei coverture{/i}. L’any 1859, les Dames varen traslladar-se al 19 de Langham Place, domicili de {i}The English Woman’s Journal{/i}. Anys més tard, varen fer campanya pel sufragi femení, que portà a l’aprovació l’any 1870 de la {i}Llei de Propietat de les Dones Casades{/i} ({i}Married Women’s Property Act{/i}), en la qual s’establia que elles tenien el dret a conservar els seus propis guanys, propietats, ingressos per renda i inversió, i herències inferiors a dues-centes lliures. No obstant això, la situació no canvià fins l’amplicació de la llei l’any 1882."
        },
        21: {
            "name": "Margaret Sanger",
            "content": "Fins que Margaret Sanger no vinculà l’emancipació de la dona amb el control de la natalitat, moltes altres feministes eren contràries a la contracepció, ja que la consideraven una pràctica corruptora que animaria a les dones a ser sexualment més actives i donaria als homes una llibertat sexual sense límits dins i fora del matrimoni. Desafiant la {i}Llei Comstock{/i} ({i}Comstock laws{/i}), que qualificava com immoral la difusió d’informació sobre mètodes contraceptius, escrigué articles explícits sobre sexe i contracepció per a dones, i realitzà gires de conferències a les quals assistien sovint dones de classe treballadora. L’església catòlica s’oposà a l’ús d’aquests mètodes i, malgrat en la dècada de 1930 comencés a ser socialment acceptat, només ho era per les dones casades. No va ser fins 1960 amb el moviment de demanda de drets reproductius que les dones solteres varen poder gaudir-ne també."
        },
        22: {
            "name": "Mary Astell",
            "content": "Mary Astell va destacar a Gran Bretanya per defensar en els seus escrits que les dones eren tan capaces d’un pensament crític i clar com els homes, i que l’aparent inferioritat era causada pel control masculí i el limitat accés a l’educació de les dones. Es va enfrontar a la postura eclesiàstica que considerava el paper secundari de la dona com un fet de disposició divina, argumentant que Déu havia creat la dona amb una ànima igualment intel·ligent i dotada de pensament. L’any 1694 escriu {i}Una Proposta Seriosa per a Dones{/i} ({i}A Serious Proposal to the Ladies{/i}), obra en la qual instava les dones a aprendre a desenvolupar el seu intel·lecte i habilitats, i a no delegar sempre en els homes."
        },
        23: {
            "name": "Mary Wollstonecraft",
            "content": "L’any 1792, Mary Wollstonecraft va escriure {i}Vindicació dels drets de la dona{/i} ({i}A Vindication of the Rights of Woman{/i}) com a reivindicació per l’emancipació femenina en l’àmbit domèstic. Insisteix en la importància de l’educació, afirmant que, des de la infància, a les nenes se les ensenya a viure subordinades i amb el sentiment d’inferioritat. Exposant {i}una revolució dels modals femenins{/i}, descriu l’empoderament de les dones com a eina per poder deixar de ser dependents de l’aprovació masculina i poder accedir a l’esfera pública, ja que una vida limitada i restringida únicament a l’àmbit domèstic acaba danyant-les psicològicament. Fa èmfasi en la cultivació personal i intel·lectual de la dona, més enllà dels estereotips de gènere i l’aparença física. D’aquesta manera, creu en una educació igualitària per homes i dones, i proposa la coeducació."
        },
        24: {
            "name": "Marxisme i feminisme",
            "content": "En el {i}Manifest comunista{/i} ({i}Manifest der Kommunistischen Partei{/i}) de 1848, Karl Marx i Friedrich Engels afirmen que el capitalisme oprimeix les dones, tractant-les com a ciutadanes subordinades de segona classe, tant en família com en societat; la dona és un simple instrument de producció. En canvi, les feministes marxistes creien que en una societat capitalista les dones servien com a reservistes del treball, a qui es recorre quan sorgís la necessitat i a qui s’excloïa quan aquesta desapareixia. Identifiquen el capitalisme i el patriarcat com el sistema dual subjacent a l’opressió de les dones. Dones socialistes i comunistes, teòriques líders del moviment comunista internacional, varen madurar qüestions com l’empoderament femení i el sufragi universal, destacant Clara Zetkin i Rosa Luxemburg  a Alemanya i Aleksandra Kollontay a Rússia."
        },
        25: {
            "name": "{i}Mujeres Libres{/i}",
            "content": "{i}Dones Lliures{/i} ({i}Mujeres Libres{/i}) és un dels grups anarcofeministes més representatius. Es formà a Espanya l’any 1936, al començament de la Guerra Civil Espanyola. Les seves fundadores eren membres de la {i}Confederació Nacional del Treball{/i} (CNT). Les anarquistes lluitaven per la revolució social, però emfatitzaven que aquesta no s’aconseguiria mentre la CNT fos majoritàriament masculina. El grup exigí que la CNT abordés amb urgència la {i}qüestió femenina{/i}, que, malgrat lluitava per la igualtat de gènere, rebutjava l’etiqueta feminista perquè considerava el femenisme de l’època massa burgès per no criticar ni el capitalisme ni el sistema de classes. {i}Dones Lliures{/i} dugué a terme dues estratègies: la captació, per atraure a dones a la lluita anarquista contra el capitalisme patriarcal gràcies al qual sempre serien esclavitzades, i la capacitació, per ajudar-les a realitzar el seu potencial."
        },
        26: {
            "name": "Nana Asma'u",
            "content": "Nana Asma’u, del califat de Sokoto, destacada per la seva posició com a filla del califa i per la seva saviesa, considerava que l’educació de les nenes havia d’instucionalitzar-se. D’aquesta manera, va crear una xarxa de mestres itinerants conegudes com a {i}jajis{/i}, la missió de les quals era recórrer l’imperi amb la finalitat d’instruir a les dones dins de les seves pròpies cases. Avui dia, el llegat d'Asma'u encara és vigent amb un grapat d’escoles i organitzacions femenines nigerianes que duen el seu nom i record. Així, el seu llegat és una recordatori de l’educació per a tothom en l’islam."
        },
        27: {
            "name": "Naomi Wolf",
            "content": "Naomi Wolf escrigué {i}The Beauty Myth{/i} l’any 1990. Les normes de bellesa imposades per la societat patriarcal diuen a les dones que s’han d’esforçar per aconseguir un ideal femení impossible. S’esclavitzen pel seu aspecte físic i s’allunyen de poder gaudir d’una vida plena i de l’activitat feminista. Així, aquest mite impacta econòmicament a les dones com a individus i a la societat capitalista en general; històricament, perquè la convertia en mercaderia, ja que la seva seguretat econòmica depenia de la mesura en què s’adeqüés a l’ideal, i ara en el seu consum de productes i serveis. D’aquesta manera, el mite oprimeix la dona en l’àmbit de la feina, la cultura i la religió, el sexe i l’alimentació, atrapant-la mitjançant els cosmètics, la dieta, l’exercici i la cirugia. L’autora proposa un futur feminista en el qual el valor de les dones depengui d’una definició pròpia de bellesa. Les dones han de tenir opcions i ser reconegudes com a persones multidimensionals, respectades per la societat com a cabals i sexuals, i tenir una vida rica i plena. No importa l’aspecte per sentir-se bella."
        },
        28: {
            "name": "Nawal El Saadawi",
            "content": "L’any 1972, Nawal El Saadawi va escriure {i}Dones i sexe{/i}, obra en la qual detalla totes les maneres en què eren oprimides les dones egípcies, entre elles les pràctiques de mutilació genital. És metgessa i activista pels drets de les dones de tendència marxista, i fou empresonada en ocasions vàries. Ella rebutjava la interpretació masculina de l’islam, ja que creia que l’alliberació de les dones no tenia cabuda en la teologia islàmica. Les seves idees es comprenen en la branca secular del feminisme en el món àrab, és a dir, són inspirades en idees occidentals. L’any 1982 fundà l’{i}Associació Solidària de Dones Àrabs{/i} ({i}Arab Women Solidarity Association{/i})."
        },
        29: {
            "name": "{i}NOW 1966 Statement of Purpose{/i}",
            "content": "L’any 1966 es fundà NOW, {i}National Organization of Women{/i}, organització basada en el principi de que totes les dones són, per sobre de tot, éssers humans que han de tenir l’ocasió de desenvolupar el seu potencial humà en la seva plenitud. Així, l’objectiu d’aquesta és prendre mesures per a què les dones participin en tots els àmbits de la societat, exercint tots els seus privilegis i responsabilitats en una relació d’igual a igual amb els homes. Sota el seu punt de vista, les dones poden assolir aquesta igualtat si són considerades per la presa de decisions en la vida política, social i econòmica nord-americana. D’aquesta manera, els seus membres s’organitzen per iniciar o recolzar accions amb la finalitat de trencar amb els prejudicis i la discriminació contra les dones en qualsevol àmbit important en la societat nord-americana."
        },
        30: {
            "name": "Paula Gunn Allen",
            "content": "A {i}The Sacred Hoop: Recovering the Feminine in American Indian Traditions{/i} (1986), Paula Gunn Allen reivindica les riques tradicions matriarcals de les dones indígenes, que desenvolupen en les seves comunitats rols de lideratge social, polític i espiritual des de molt abans que es produís la colonització europea. Fa èmfasi en la tradició de poder de les natives americanes i assenyala que les idees contemporànies sobre el gènere estan molt influenciades per les nocions patriarcals de génere introduïdes pels colons europeus."
        },
        31: {
            "name": "Olympe de Gouges",
            "content": "L’any 1791, Olympe de Gouges, autora teatral i activista, va redactar la {i}Declaració dels drets de la dona i de la ciutadania{/i} ({i}La déclaration des droits de la femme et du citoyenne{/i}) amb la finalitat de reivindicar drets iguals per a les dones. Aquest fet es va dur a terme temps després de que la {i}Declaració dels drets de l’home i del ciutadà{/i} ({i}La déclaration des droits de l’homme et du citoyen{/i}) de 1789 afirmés els drets i la llibertat de tots els homes. En la seva obra, de Gouges va apel·lar als valors de la Il·lustració (els principis igualitaris i l’individualisme) per tal d’exigir els mateixos drets per a les dones. Així, de Gouges va ser detinguda per criticar el govern i fou executada a la guillotina el 1793 durant l’època de Terror de la Revolució Francesa."
        },
        32: {
            "name": "{i}Riot Grrrl Manifesto{/i}",
            "content": "L’any 1991, es publicà el {i}Riot Grrrl Manifesto{/i} en el {i}Bikini Kill Zine 2{/i}, en el qual es donaven setze raons de l’esperit de {i}Riot Grrrl{/i} que responen al lema {i}Dones, sexe i rock and roll{/i}. Exigeixen poder compartir experiències, estratègies i maneres de fer amb les altres dones, crear formes de ser no patriarcals i de fer música, amigues i escenes basades en la comunicació i la comprensió enlloc de la competència i les categoritzacions, exigeixen no voler viure esclavitzades als ideals de l’home ni a les seves inseguretats, sinó ser qui somnien ser, estableixen que les {i}riot grrrl{/i} busquen salvar la vida psicològica i cultural de totes les dones del món, exigeixen la promoció i el suport entre dones i artistes de tota mena com a part integral del procés, estableixen el seu odi al capitalisme en totes les seves formes, i exigeixen poder validar-se i enfortir-se dins de la comunitat femenina fent, llegint, veient i escoltant. I, per últim, creuen que les dones constitueixen l’ànima de la força revolucionària que pot canviar i canviarà el món de debò."
        },
        33: {
            "name": "Shulamith Firestone",
            "content": "L’any 1970, es va publicar {i}The Dialectic of Sex{/i}, de Shulamith Firestone.  Diu que estimar resulta ser una relació de poder, i la desigualtat entre homes i dones fonament de totes les formes socials d’opressió, en les quals s’inclou la família nuclear. Reclama la criança dels infants amb neutralitat de gènere, i proposa l’abolició de la família nuclear per parelles igualitàries no casades i col·lectius que criïn plegats els infants. Així mateix, considera que les dones han de tenir més drets i llibertat d’expressió. En conclusió, esmentà que l’origen de l’opressió recau en la divisió sexual."
        },
        34: {
            "name": "Sojourner Truth",
            "content": "Sojourner Truth fou un símbol pel feminisme antiesclavista i una figura fonamental pel moviment abolicionista. Va néixer esclava però va aconseguir fugir l’any 1826. En la {i}Convenció pro Drets de les Dones{/i} de 1851, va exposar un discurs memorable per la igualtat de les dones, en el qual es declarà igual als homes en força i intel·lecte. Ja no només es reiterava la demanda de sufragi femení, sinó que es feia èmfasi en la igualtat davant la llei sense distinció de sexe ni color, unint així la lluita pels drets de les dones i la lluita per la llibertat dels afroamericans esclavitzats en el moviment abolicionista. En aquest cas, les dones eren doblement discriminades: per la seva condició de dona i pel seu color de pell."
        },
        35: {
            "name": "Sophia Elisabet Brenner",
            "content": "Sophia Elisabet Brenner va ser una de les primeres dones en reivindicar públicament que homes i dones mereixien els mateixos drets. L’any 1693, va publicar el poema {i}La defensa justificada del sexe femení{/i} ({i}Det Qwinliga Könetz rätmätige Förswar{/i}), en el qual esmentava que la dona era intel·lectualment igual a l’home. A més a més, també defensava en altres escrits que homes i dones eren iguals en tot menys en l’aparença física."
        },
        36: {
            "name": "Sufragisme",
            "content": "El moviment sufragista fou una iniciativa de finals del segle XIX i principis del XX. Les sufragistes, liderades per Millicent Fawcett i constituents de la {i}Unió Nacional de Societats de Sufragi Femení{/i} (NUWSS), de la qual quasi tots els seus membres eren de clase mitjana o alta, apostaven per una activitat no agressiva mitjançant peticions pacífiques i mítings públics. En canvi, les {i}suffragettes{/i}, liderades per Emmeline Pankhurst i constituents de la {i}Unió Social i Política de les Dones{/i} (WSPU), de la qual alguns membres busquen atraure’s a la classe obrera, aposten per l’acció directa (violència política) per aconseguir publicitat sota el lema {i}Fets, no paraules{/i}. D’aquesta manera, moltes de les {i}suffragettes{/i} varen ser empresonades, alimentades forçosament quan feien vaga de fam a la presó, assassinades, o varen perdre la vida en la lluita per la causa. Destaquen el cas de Emily Wilding Davison i el de Mary Richardson."
        },
        37: {
            "name": "Susan Faludi",
            "content": "L’any 1991, es publicà {i}Backlash: The Undeclared War Against American Women{/i}, de Susan Faludi. Identifica la {i}Nova Dreta{/i} i la seva agenda profamília com a motor de la reacció, que atribueix a la por a l’èxit del feminisme. Critica la bretxa salarial creixent i la hipocresia dels {i}emisaris de la reacció{/i} que impedien aprovar projectes de llei per millorar l’assistència infantil alhora que culpaven les mares treballadores de ser males o les animaven a reprendre els rols tradicionals. Fa èmfasi en el rol dels mitjans de comunicació com a estímul de la reacció antifeminista, que assumeix la construcció de la imatge de la dona treballadora com a insatisfeta i que difón mites sobre {i}l'escassetat d’homes{/i} o els {i}ventres estèrils{/i}. En la moda i la cultura popular, es dóna pas a siluetes cenyides i amb roba poc pràctica, i al cinema es retrata a les professionals solteres com a dones desagradables o malèvoles. Així mateix, comenta el pic de cosmètics i cirugia plàstica a causa de la pressió de semblar jove, criticant també la psicologia pop i els llibres d’autoajuda."
        },
        38: {
            "name": "Suzanne Voilquin",
            "content": "L’any 1832, Suzanne Voilquin va començar a treballar com a editora en la revista feminista de classe treballadora {i}La Tribune des femmes{/i}. Ella va decidir viure de manera independent, ja que volia ser un exemple per altres dones com a defensora dels valors sansimonians, sobretot després de la Revolució de 1830. El moviment sansimonià promovia un estil de vida comunal, lliure de la tirania del matrimoni, en el qual els principis femenins de la pau i la compassió substituïen els valors masculins més agressius."
        },
        39: {
            "name": "Virginia Woolf",
            "content": "En {i}Una cambra pròpia{/i} ({i}A Room of One’s Own{/i}, 1929), Virginia Woolf va exposar les dificultats que tenien les escriptores per assolir el mateix èxit que els homes. Proposa que les dones necessiten un espai, que dóna nom a l’obra, per poder desenvolupar la seva creativitat, lliures de lligams domèstics. Per a ella, la independència econòmica era necessària per aconseguir-ho, sent inclús més important que el vot. Quan tinguessin aquest espai per pensar, les dones podrien experimentar i desenvolupar un llenguatge femení absent fins llavors en la literatura. Suggereix que les escriptores haurien d’entaular una lluita interior contra l’ideal femení victorià, exemplificat en la muller i mare perfecta."
        }
    }
