
## Dictionary in English for all items of glossary.


init -10 python:
    glossary_dict_en = {
        0: {
            "name": "Adrienne Rich",
            "content": "{i}Compulsory Heterosexuality and Lesbian Existence{/i} (1980), essay written by Adrienne Rich, establishes the obligatory heterosexuality as a capitalist mechanism to impose the women economic subordination to men in marriage and maternity. Patriarchal exploitation and abuse has caused, as she wrote, women to internalize the idea that they are sexual objects and to accept the breach of their limits by men in order to survive. This way, she proposes a woman who identifies as so and who loves other women as well, which she calls {i}continuous lesbianism{/i}."
        },
        1: {
            "name": "Aleksandra Kollontay",
            "content": "Aleksandra Kollontay was an advocate for a structured and more fair society where the State supports the women, especially working mothers, and those had the same political and legal rights than of the men. In 1909 she wrote {i}The Social Basis of the Woman Question{/i}, a work in which she proposes measures like State economic aid to pregnant and lactating women, socialization of domestic works and child care, which she considered it was a social responsibly and not individual, so this allowed women to contribute both politically and economically to the State."
        },
        2: {
            "name": "Alicia Walker",
            "content": "According to Alicia Walker, feminism dominated by middle class white women ignores racism while contributing to it. Black women, besides gender inequality, suffer racial inequality and so they are more oppressed. Because of this, she establishes that they require a proper feminism, called {i}womanism{/i} (1983), that takes into account gender, racial and class oppression. This way, {i}womanism{/i} aims to fight for the life of black women and to contribute to the ways they survive to their multiple oppressions. With this spectrum of actions, she emphasizes in the {i}womanish{/i}, in those who question themselves, in love to other women and beings and in self-healing through love to spirituality, dance and music. So, {i}womanism{/i} places a bid for the renounce of class divisions, the promotion of gender equality, the sexuality freedom and refusal of racism."
        },
        3: {
            "name": "Angela Davis",
            "content": "In 1981 was published {i}Women, Race and Class{/i}, by Angela Davis. This essay prompts that feminism is full of prejudices on race and gender. At the same time, she also states how the slavery subdued black women with inhuman manners that reflected very different assumptions about feminity, race and gender. This way, she exposes the reasons why black women's vindications were systematically made invisible even with their hidden revolutionary potential. Besides making manifest the fighting strategies of black women, she also exposes the composition troubles of the differences that nowadays still rip apart the political movements."
        },
        4: {
            "name": "Anne Koedt",
            "content": "Men called {i}frigid{/i} to the women who could not have vaginal orgasms. This is so much that women were sexually defined by whatever pleases men, in other words, sexuality is politics. Anne Koedt, author of {i}The Myth of the Vaginal Orgasm{/i} (1968), exposes that vaginal stimulation is not enough by itself because it doesn't stimulates the clitoris; therefore, there is no orgasm. The fact that men call {i}frigid{/i} to the women blames them. This way, men keep the myth of the vaginal orgasm because of their own predominant desire of penetration and, at the same time, by fear to be expendable."
        },
        5: {
            "name": "Betty Friedan",
            "content": "Betty Friedan, from a psychosocial standpoint of the way of life that of the women, deciphers the oppressive and suffocating role they have imposed and analyzes their discomfort and dissatisfaction. The main problem is a political one, because the concept of woman equals to mother and wife, which cuts down every chance of personal fulfillment and blames all those who are not happy living only for the others. This unhappy feeling of the women is called {i}the problem with no name{/i}. The idealized picture of feminity rooted in marriage and family was still present among women, which the autor mentioned in her book {i}The Feminine Mystique{/i} (1963). To the former reasons of women discomfort, it must be added their infantilization, the gender courses at schools, their renounce to a professional career and the attribution of a mere sexual and biological function to them. She proposes formation and a paid job as their way out."
        },
        6: {
            "name": "Cyberfeminism",
            "content": "Cyberfeminism is the conjunction of feminism and cyberspace including the parts of creation, alternative information and social activism and it is contextualized in the scope of arts, politics and science. Its purpose suggests a political demand or strategy. Evenmore, there is a double way: one for mobilization and other one for counter-information and alternative information, breaking the control barrier from the mass media.\nThis concept was coined by the VNS Matrix collective in 1991, the same year they published {i}The Ciberfeminist Manifesto for the 21st Century{/i}, where they propose the concept as a cooperation between women, machine and new technologies. Years after, they designed an \"anti-videogame\" from a femenist optics, which goal was to built a cyberspace identity far from masculine myths through the IT.\nIn 1993, the Women's Networking Support Programme (APC WNSP) was started with the goal of using the new technologies for women's empowering, developed from a gender and an strategic usage of social networks perspective."
        },
        7: {
            "name": "Catherina Ahlgren",
            "content": "Catherina Ahlgren, friend of Charlotta Nordenflycht, published in 1772 a series of rethoric letters, addressed to both men and women, under the alias {i}Adelaide{/i}, in which she talked about friendship, moral considerations and advices addressed to everyone's daughters, and about true love, concept that only extists when a man and a woman treat each other as equals. Moreover, she advocated for social activism, democracy, gender equality and women solidarity respect of male domination. In 1782, she was a editor at {i}Of the Art to Please Properly{/i} ({i}Om att rätt behaga{/i}), one of the first Finnish newspapers."
        },
        8: {
            "name": "Clara Campoamor",
            "content": "Clara Campoamor began to get interested in women's rights while she was working at the newspaper {i}La Tribuna{/i}. Motivated by an increasing political curiosity, she achieved to be the first female member at the Supreme Court of Spain. In 1931 she was part of the task force to elaborate the Constitution for the new Republic, and it was because of her the universal suffrage was included. With the upcoming of Franco's dictatorship, this and many more progresses were revoked. Clara Campoamor was exiled when the Spanish Civil War began and General Franco never let her come back."
        },
        9: {
            "name": "{i}Consciousness-Raising{/i}",
            "content": "In 1967 arose the concept of {i}consciousness{/i} relative to the main task of feminists: to wake a {i}class consciousness{/i} among women. This way, one of the methods to spread the cause of the liberation movement for the women was the {i}consciousness-raising{/i}. This method, that helped to improve women's self-esteem by being recognized as a self entity, consisted in meeting together to talk about their experiences, from childhood to marriage and sexuality, aiming to prove that personal difficulties were rooted to political questions that should change; {i}the personal is also political{/i}. It wasn't just necessary to transform the public space, but the private space as well. The power relations that structures the family and sexuality were focus of submission to women, meanwhile men took in the economic, sexual and psychologic benefits of the patriarchal system."
        },
        10: {
            "name": "{i}Seneca Falls Convention{/i}",
            "content": "The {i}Declaration of Rights and Sentiments{/i} was signed at {i}Seneca Falls Convention{/i} in July 19th, 1848. The impetus for this convention came from the political activism against slavery and the goal was to fight the lack of social, civil and religious rights of the women. Lucretia Mott was the first president of the {i}American Equal Rights Association{/i}, that advocated for universal suffrage. Years after, the association splitted, due to the AERA decission of prioritizing afro-american male suffrage, into the {i}National Women's Suffrage Association{/i}, in which there was Elizabeth C. Stanton and Susan B. Anthony, that advocated for women's suffrage at federal level and the {i}American Women's Suffrage Association{/i}, where there were Charlotte Woodward Pierce and Lucy Stone, that fights for universal suffrage at state level. In 1890 both merged into the {i}National American Women's Suffrage Association{/i}. Charlotte Woodward was the only signatory who lived until the 19th Amendment, but an illness impeded her to vote."
        },
        11: {
            "name": "{i}Coverture{/i}",
            "content": "The {i}Coverture{/i} law establishes that women's rights, properties, possessions, money and heritages passes down to the husband when they marry. Moreover, the husband has legal protection to abuse and deprive his wife from freedom in order to ensure her fulfillment on her domestic and sexual duties, and has exclusive custody of their children. Divorce required a private law from the Parliament that, even being a legal separation, it was exceptional and expensive and the husband could require by {i}criminal conversation{/i} his wife's suspect sexual affairs. For women they could only expect serious cruelty, incest and bigamy as causes for divorce. Only four women demanded divorce between 1765 and 1857."
        },
        12: {
            "name": "Ecofeminism",
            "content": "Ecofeminism claims that it is all social processes in economy which base the dignified lifes of the people, as well as a substainable relationship with nature. It denounces the usage of toxics in food, cosmetics or cleaning products, to the pathologization and medicalization of our bodies for pharmaceutical companies' profit. This way, it denounces the colonialist effects of free trade treaties, the extractivism and the super-projects that plunder the local resources from the communities. Furthermore, it manifests the lack of political responsibility towards the severity of energy crisis and the permissibility with energy corporations' profit, and emphasizes the way agriculture, livestock and agri-food industry, all highly masculinized, impose unhealthy products and stop the development of other farming models, more healthy and with higher femenine presence. Lastly, ecofeminism is against war culture and the arms industry."
        },
        13: {
            "name": "Elizabeth Montagu and the {i}Bluestockings{/i}",
            "content": "Elizabeth Montagu, also known as {i}Queen of the Blues{/i}, was the host at the most prestigious salon in Mayfair (Londres), which lasted for fifty years. In 1750, she founded the {i}Blue Stockings Society{/i} along with Elizabeth Vesey, a name that refferences the men's prefference for the blue wool stockings, instead of the day-to-day black silk ones, which allowed to represent the rather informal feeling of the meetings. These women hosted both men and women with the main goal of promoting a {i}rational dialogue{/i} from which they could extract the moral progress. The objectives of the {i}Bluestockings{/i} were to promote the discussion about arts and literature, to offer a space where men and women could talk as equals, to ensure mutual support to the women who were looking for writing and publishing, as well as to promote social meetings where the stimulus of the talking were the substitute for games and alcohol."
        },
        14: {
            "name": "Emma Goldman",
            "content": "Emma Goldman was the precursor of the anarcho-feminism, which ideological roots dates back to the working class movements in late XIX and early XX century. Her anarchist feminism proposed fighting the exploitation from the employers to their employees, from government / army to civil population, and the historic submission to the women from capitalist patriarchy. Moreover, she defended a greater freedom in sexual relations, more aid to working class mothers and pregnancy prevention."
        },
        15: {
            "name": "Germaine Greer",
            "content": "In 1970 was published {i}The Female Eunuch{/i}, by Germaine Greer. It mentions that women are castrated both socially, sexually and culturally. Greer emphasizes that they must learn to question the femenine {i}normality{/i}, because she states that the most valued qualities in a woman are those of an eunuch: shyness, languor and delicacy. Not only that, but women are conditionated with the use of stereotypes to avoid thinking by themselves, to not to behave independently and to see themselves illogical, subjectives and fool. Even love has been corrupted by romantic myths and pornography. She criticizes the nuclear family by being harmful; love becomes a symbol of hate, disgust and aversion. Finally, she establishes that no woman should maintain any patriarchal relationship, but they must open themselves towards social and sexual freedom."
        },
        16: {
            "name": "Harriet Taylor Mill and John Stuart Mill",
            "content": "Harriet Taylor Mill was an activist who demanded equality with men in all rights (political, civil and social), as she wrote in her essay {i}The Enfranchisement of Women{/i} in 1851. Moreover, she believed that contributing to the family earnings would make that the woman were more respected by her husband, who he would see her more as a partner than as a domestic servant. Together with her husband, John Stuart Mill, in 1832 she wrote {i}Early Essays on Marriage and Divorce{/i}, in which she inquired in a new way to understand and live with couple that doesn't suppose the slavery to the woman, but a deal between equals, because both considered that women are free individuals and they had to have economic independence."
        },
        17: {
            "name": "Hedvig Charlotta Nordenflycht",
            "content": "Hedvig Charlotta Nordenflycht, Swedish writer and intellectual, debuted literily 1742 with {i}The Mourning Turtledove{/i} ({i}Den sörjande Turturduvan{/i}), in which she claimed for further rights for her own sex. Some years after that, in 1753 she was the first woman accepted within the {i}Tankebyggararorden{/i} ({i}Order of the thought constructors{/i}), a literary group in the city of Stockholm that aimed for a reform in the Swedish literature. With works such as {i}Women's duty to train their sense{/i} ({i}Fruentimbers Plikt att upöfwa deras Wett{/i}, 1744) to defend the women intellect or {i}To the Defense of Women{/i} ({i}Fruntimrens försvar{/i}, 1761) to disprove misogyny, she vindicated the right to be intellectualy active. She also signed its own works with her own birthname."
        },
        18: {
            "name": "Kimberlé Crenshaw",
            "content": "Specialist in critic theory of race, Kimberlé Crenshaw defined the term {i}intersectionality{/i}. In her 1991 essay, {i}Mapping the Margins: Intersectionality, Identity Polotics and Violence against Women of Color{/i}, she divided it into three types. Structural intersectionality refers to the different oppression exercised upon white women and upon black women. Political intersectionality is related to the impact of the law and public politics upon women of color, regardless if those are inspired in feminist or aniracist motivations. And finally, representative intersectionality refers to how women of color are represented in popular culture and how that affects in their daily lifes. This way, she establishes that the multiplicity of the oppression should not have an additive approach, but it should be understood how race complicates class oppression, gender complicates racial oppression, and so on."
        },
        19: {
            "name": "{i}La Liberté guidant le peuple{/i}",
            "content": "The painting {i}Liberty Leading the People{/i} ({i}La Liberté guidant le peuple{/i}) was painted by Eugène Delacroix to represent Liberty as a guide who leads the people, formed by middle and lower social class members, in July 28th during the Revolution of the {i}Three Glorious{/i} ({i}Trois Glorieuses{/i}). In this way, the idea of liberty is represented by a woman gifted with great beauty."
        },
        20: {
            "name": "{i}La Tribune des femmes{/i}",
            "content": "{i}La Tribune des femmes{/i} was the first working class women magazine which spreaded the Saint-Simonianism values and invited the women, from every social class, to contribute to their own social progress. This way, it was proposed an alliance between proletarian and privileged women that aimed to create a {i}new woman{/i} because the oppression links every woman alike, regardless their own social class. This constituted the first attempt to create a femenine conscience."
        },
        21: {
            "name": "{i}Ladies National Association{/i}",
            "content": "in 1869 Josephine Butler founded the {i}Ladies National Association for the Repeal of the Contagious Diseases Acts{/i}, acts thet pretended to control the propagation of infectious diseases among the army by authorizing forced medical checks to prostitutes. She argued that those were unfair and proved the double sexual standards because those punished the victims of male exploitation, the women, while the perpretators, the men, were unpunished. Moreover, those acts exposed a class bias because those protected higher class men and persecuted working class women, which made the protitutes a slave class to please men."
        },
        22: {
            "name": "{i}Langham Place Group{/i}",
            "content": "The {i}Langham Place Group{/i} was the first feminist activist group in United Kingdom. They were middle class instructed women who formulated requests to reform the laws regarding married women. Partly thanks to this activism the {i}Matrimonial Causes Act{/i} was passed in 1857, which led to the first divorces tribunal in Great Britain and being the first step to abolish the {i}Coverture Law{/i}. In 1859 the group moved to Langham Place 19th, address of {i}The English Woman's Journal{/i}. Years thereafter they campaigned for women's suffrage, which led in 1870 to the approval of the {i}Married Women's Property Act{/i} in which there was established that women had the right to keep their own earnings, properties and heritages below two hundred pounds. Nevertheless, women's situation wouldn't change until the law was extended in 1882."
        },
        23: {
            "name": "Leora Tanenbaum",
            "content": "In {i}Slut! Growing Up Female With a Bad Reputation{/i} (1999), Leora Tanenbaum exposes how victims of sexual violence are divided in good or bad. {i}Bad{/i} survivors are those accused of wearing provocative clothing, not having resisted enough or being very sexually active and, this way, they are not considered victims."
        },
        24: {
            "name": "Margaret Sanger",
            "content": "Until Margaret Sanger linked women enfranchisement to natality control many other feminists were adverse to contraception, because they considered that a corrupt practice that would encourage women to be more sexually active and would give men a limitless sexual freedom in and out of matrimony. To challenge the {i}Comstock laws{/i}, which rated as immoral the spread of information about contraceptive methods, she wrote explicit articles about sex and contraception for women and arranged conference tours to which there often assisted working class women. The Catholic Church opposed to these methods and, even if in the 1930s began to be widely accepted, that was only for married women. It wasn't until the 1960s with the movement for the reproductive rights that single women could make use of those methods as well."
        },
        25: {
            "name": "Mary Astell",
            "content": "Mary Astell was highlighted in Great Britain for defending in her writing that women are as capable as men for the critical thinking, and that the apparent inferiority was caused by the male control over them and the limited access to education for women. She faced against the Church ideas which considered the secondary role of the women as a divine fact, arguing that it was God itself who created the woman with an equal intelligent soul and gifted with thought. In 1694 she wrote {i}A Serious Proposal to the Ladies{/i}, a work in which she urged women to learn how to develop their intellect and habbilities and to not to always delegate in men."
        },
        26: {
            "name": "Mary Wollstonecraft",
            "content": "In 1792, Mary Wollstonecraft wrote {i}A Vindication of the Rights of Woman{/i} as a claim for femenine emancipation in the domestic sphere. She insisted in the key role of education asserting that, from childhood onwards, girls were thaught to live subordinates and with sense of inferiority. By exposing {i}a revolution of the femenine manners{/i}, she described the women empowering as a tool to not to be dependent upon men approval anymore and to be able to access to the public sphere, because a life restricted and limited only to the domestic sphere will end psycologically damaging them. She emphasises in personal and intellectual growth of the women beyond gender and physical looking stereotypes. This way, she believed in an egalitarian education for men and women and proposes the co-education."
        },
        27: {
            "name": "Marxism and feminism",
            "content": "In the 1848 {i}Communist Manifest{/i} ({i}Manifest der Kommunistischen Partei{/i}), Karl Marx and Friedrich Engels stated that capitalism oppresses women, treating them as a second class subordinate citizen, in family as in society; women are just another production instrument. Instead, marxist feminists believed that in a capitalist society women were working reservists, who do the society turn to when there was a need and who were excluded when there wasn't. Socialist and communist women, theoretical leaders from the international communist movement, matured questions as female empowerment and universal suffrage, in where Clara Zetkin and Rosa Luxemburg, in Germany, and Aleksandra Kollonay, in Russia, were highlighted."
        },
        28: {
            "name": "{i}Mujeres Libres{/i}",
            "content": "{i}Free Women{/i} ({i}Mujeres Libres{/i}) were one of the most outsanding anarcho-feminist groups. It was founded in Spain in 1936, at the beginning of the Spanish Civil War. The founders were members of the {i}Confederación Nacional del Trabajo{/i} ({i}National Work Confederation{/i}). Anarchists fought for social revolution, but they highlighted the fact that it could not be achieved meanwhile CNT was mostly masculine. This group demanded that CNT to urgently approach the {i}women question{/i} that, even fighting for gender equality, refused the feminist tag because they considered that the feminism of that time was very bourgeois for not criticizing neither the capitalism nor the class system. {i}Free Women{/i} executed two strategies: acquisition to attract women to the anarchist fight against partiachal capitalism, were they would always be slaves, and training to help them achieve their full potential."
        },
        29: {
            "name": "Nana Asma'u",
            "content": "Nana Asma’u, from the Caliphate of Sokoto and highlighted for her position as a Calipha's daughter as well as for her wisdom, considered that girls education should be a matter of state. This way, she created a network of traveling teachers known as {i}jajis{/i}, whose mission was to travel across the empire in order to instruct the women in their own homes. Nowadays the legacy of Asma'u is still alive in a handful of schools and femenine organisations in Nigeria that carry her name and memory. So her legacy is a reminder for everybody's education across the Islam."
        },
        30: {
            "name": "Naomi Wolf",
            "content": "Naomi Wolf wrote {i}The Beauty Myth{/i} in 1990. The rules of beautiness imposed by the patriarchal society tells to the women they must strive to achieve an impossible femenine ideal. They enslave themselves by their physical appearance and they keep away from having a full life and from feminist activities. So this myth economically impacts to women as individuals and capitalist society in general; historically, because it converted them in commodities, as their economical security depended upon how close they are to that ideal, and now upon their consumption of goods and services. This way, the myth opresses women in the scopes of work, culture and religion, sex and food, trapping them through cosmetics, diet, physical exercise and plastic surgery. The autor proposes a feminist future in which the value of the women would depend upon an own definition of beautiness. Women have to have multiple chioces and must be recognized as multidimensional persons, to be respected by the society as thorough and sexual people, and to have a full life. The appearances doesn't matter to feel beauty oneself."
        },
        31: {
            "name": "Nawal El Saadawi",
            "content": "In 1972 Nawal El Saadawi wrote {i}Women and sex{/i}, in which work she details every way the Egyptian women were oppressed, genital mutilation among them. Of a marxist inclination, she is medical doctor and activist pro rights of women and was imprisoned several times. She rejects the masculine interpretation of the Islam because she believed that women liberation could not fit into the islamic theology. Her ideas are comprised among the secular branch of the feminism in the arabic world, in other words, are influenced by western ideas. In 1982 founded the {i}Arab Women Solidarity Association{/i}."
        },
        32: {
            "name": "{i}NOW 1966 Statement of Purpose{/i}",
            "content": "In 1966 there was founded NOW, {i}National Organization of Women{/i}, organization based upon the principle of that women are, above everything else, human beings that must have the chance to fully develop their human potential. So the main goal is to take measures so women could participate in every ambit of society, making use of their privileges and responsibilities in a relationship from equal to equal with men. By their point of view, women can achieve this equality if they are considered by their decision making in the political, social and economic American life. This way, its members organize to start or to support actions with the aim of breaking with prejudices and discrimination against women in any important ambit in the American socierty."
        },
        33: {
            "name": "Paula Gunn Allen",
            "content": "In {i}The Sacred Hoop: Recovering the Feminine in American Indian Traditions{/i} (1986), Paula Gunn Allen vindicates the rich matriarchal traditions from indigenous women, who delevop roles of social, political and spiritual leadership within their communities long before the European colonization. She emphasizes in the tradition of power of the native american women and points out that the contemporary ideas about gender are very influenced by patriarchal notions of gender introduced by European colonists."
        },
        34: {
            "name": "Olympe de Gouges",
            "content": "In 1791, Olympe de Gouges, theatre author and activist, wrote the {i}Declaration of the Rights of Woman and of the Female Citizen{/i} ({i}La déclaration des droits de la femme et du citoyenne{/i}) with the main goal of vindicate equal rights for the women. This was done some time after in 1789 the {i}Declaration of the Rights of Man and of the Citizen{/i} ({i}La déclaration des droits de l’homme et du citoyen{/i}) affirmed the rights ans liberties of all men. In her work, de Gouges appelated to the values of the Enlightenment (the principles of equality and individualism) to demand the same rights for the women. So de Gouges was detained for criticising the gorvenment and was executed by guillotine in 1793, during the Reign of Terror of the French Revolution."
        },
        35: {
            "name": "{i}Riot Grrrl Manifesto{/i}",
            "content": "In 1991, the {i}Riot Grrrl Manifesto{/i} was published at the {i}Bikini Kill Zine 2{/i}, in which there was sixteen reasons for the {i}Riot Grrrl{/i} spirit which responds to the motto {i}Dones, sexe i rock and roll{/i}. They demanded to be able to share experiences, strategies and ways to do with other women, to create non-patriarchal ways to be and to make music, friends and scenes based on communication and comprehension instead of competition and categorizations. They also demanded to not to live under the males' ideals nor their insecurities, but to be whoever they dream to be. They establish that {i}riot grrrls{/i} look for saving the psychological and cultural life of all women in the world, demanding as well the promotion and support between women and artists of all kind as a key part of the process. They settle their hate to capitalism in all its ways, and they demand to be able to validate and strengthen themselves inside the femenine community by doing, reading, watching and listening. And, last, they believe that women constitute the soul of the revolutionary force that trully can and will change the world."
        },
        36: {
            "name": "Sara Ahmed",
            "content": "In {i}Feminist Killjoys (and other Willful Subjects){/i} (2010), Sara Ahmed explores the feminism and emotions, specifically how the negative of feminists to conform with the oppression towards women breaks the social standards. She studies the everyday world as a place for power consolidation that can be questioned and shows how feminist theory is generated from the daily life and the ordinary experiences of being a feminist. Encourages to invent creative solutions, like support systems to help overcome the devastating experiences of racism and sexism, and finally mentions the confusing life to which she offers tools to live a feminist life and to strengthen the bounds between that and the feminist theory."
        },
        37: {
            "name": "Shulamith Firestone",
            "content": "In 1970 it was published {i}The Dialectic of Sex{/i}, by Shulamith Firestone. She states that to love is indeed a relationship of power and the inequality between men and women is the foundation of all social forms of oppression, in which it is included the nuclear family. She also demands raising children with gender neutrality and proposes the abolition of the nuclear family replacing it by egalitarian unmarried couples and collectives that raise together the children. This way, she considers that women should have more rights and freedom of speech. To sum up, she states that the origin of the oppression relies upon sexual division."
        },
        38: {
            "name": "Sojourner Truth",
            "content": "Sojourner Truth was a symbol for anti-slavery feminism and an important icon for the abolitionist movement. She was born as a slave, but managed to escape in 1826. At the {i}Convention for Women's Rights{/i} in 1851 she exposed a memorable speech for women equality, in which she declared herself equal to men in both strenght and intellect. There wasn't just reaffirmed the demand for women's suffrage, but it was emphasized the equality before the law without any distinction due to gender or skin colour, merging this way the fight for women's rights and the fight in the abolitionist movement for freedom for the enslaved african-american. In this case women were twice discriminated: because of being women and due to the colour of their skin."
        },
        39: {
            "name": "Sophia Elisabet Brenner",
            "content": "Sophia Elisabet Brenner was one of the first women to publicly vindicate that men and women deserve the same rights. In 1693, she published the poem {i}The justified defense of the female sex{/i} ({i}Det Qwinliga Könetz rätmätige Förswar{/i}), in which she stated that the women are intellectually equal to the men. In addition, she also defended in other writings that both men and women are the same except for their physical appearance."
        },
        40: {
            "name": "Suffragism",
            "content": "The suffragist movement was an initiative from late XIX and early XX century, The suffragist, leaded by Millicent Fawcett and being part of the {i}National Union of Women's Suffrage Societies{/i}, from which almost every member was of middle or higher class, advocated for a non-violent activity and through pacific demands and public meetings. Instead, the {i}suffragettes{/i}, leaded by Emmeline Pankhurst and being part of the {i}Women Social and Political Union{/i}, from which many members were from working class, went through direct action (political violence) under the slogan {i}Deeds, not words{/i} in order to make them being noticed. This way, many {i}suffragettes{/i} were imprisoned, being fed by force when they were on a hunger strike, murdered or killed fighting for the cause. The most iconic cases were those of Emily Wilding Davison and Mary Richardson."
        },
        41: {
            "name": "Susan Faludi",
            "content": "In 1991 it was published {i}Backlash: The Undeclared War Against American Women{/i}, by Susan Faludi. It identifies the {i}New Right{/i} and their pro-family agenda as a motor for reactionarianism, which is attributed to fear of feminism success. She criticizes the growing pay gap and the hypocrisy of the {i}reactionarianism emmisaries{/i} who impede to pass laws which could improve childcare at the same time they blame working mothers of being mean or they encourage them to retake the traditional roles. She also emphasizes the role of the media as a stimulus of the anti-feminist reaction, which assumes the construction of the image of the dissatisfied working women and which spreads myths about the {i}shortage of men{/i} or {i}barren wombs{/i}. in fashion and pop culture, it gives way to tight silhouettes and impractical clothes, and at cinema the single proffessional women are portrayed as mean or unpleasant. This way, she alludes to the peak usage of cosmetics and plastic surgery due to the pressure to look young, criticizing as well the pop psychology and self-help books."
        },
        42: {
            "name": "Suzanne Voilquin",
            "content": "In 1832, Suzanne Voilquin started working as editor at the working class feminist magazine {i}La Tribune des femmes{/i}. She decided to live her life in an independent way so that could be a model for other women as a advocate for the Saint-Simonian values, even more after the Revolution of 1830. The Saint-Simonian movement promoted a communal lifestyle in which the femenine principles of peace and compassion substituted the more aggressive masculine principles."
        },
        43: {
            "name": "Virginia Woolf",
            "content": "In his work from 1929 {i}A Room of One’s Own{/i}, Virginia Woolf exposed the difficulties the female writers had to accomplish the same success than of the male. She proposes that the women need a room, which gives its name to the work, to develop their creativity, free from domestic ties. For her, economic independence was necessary to achieve this, being even more important than the right to vote. When they had this space to think, women could experiment and develop a female language missing from literature until then. She suggested that female writers should establish an inner fight agains the victorian female ideal, exemplified in the image of the perfect wife and mother."
        }
    }
